io.github.SysDVR-Qt/linglong.yaml

CROSS-PLATFORM NETWORK FILE TRANSFER APPLICATION.
Stream Switch games to your PC via USB or network.
Log: add software name--SysDVR-Qt

build: add SysDVR-Qt

---

nitroshare-desktop/linglong.yaml

上传了一个NitroShare，使文件从一个设备传输到另一个设备极其简单。

add nitroshare-desktop

---

io.github.android-file-transfer-linux/linglong.yaml

the App of file Transfer by MPT
log: linux版的MPT协议传输APP。

build: add androidFileTransferLinux

---

cmake/linglong.yaml

某些项目需要3.26以上版本cmake.
Log: 更新了3.28的cmake

build: add cmake 3.28

---

libgit2/linglong.yaml

finish build libgit2 lib for ll-builder.
log: 完成libgit2 的编译,libgit2是gitg所必须的依赖

build: add libgit2

---

io.github.qjackctl/linglong.yaml

Provides a simple GUI dialog for setting several JACK server parameters, which are properly saved between sessions, and a way control of the status of the audio server. With time, this primordial interface has become richer by including a enhanced patchbay and connection control features.
Log: add software name--qjackctl

build: add qjackctl

---

libssh2/linglong.yaml

finish build libssh2 lib for linglong
log: deepin 社区的libssh2库（此库为编译gitg软件所必须的依赖）

build: add libssh2

---

libpcap/linglong.yaml

Libpcap, a system-independent interface for user-level packet capture. libpcap provides a portable framework for low-level network monitoring. Applications include network statistics collection, security monitoring, network debugging, etc.
Log: 添加了一个依赖库Libpcap

add libpcap

---

pkgconf/linglong.yaml

编译成功：
package compiler and linker metadata toolkit.
Log: add lib name--pkgconf

add pkgconf

---

io.github.tiny-image-finder/linglong.yaml

finish build tiny-image-finder for ll-builder.
log: 完成tiny-image-finder的编译

build: add tiny-image-finder

---

tesseract/linglong.yaml

This package contains an OCR engine - libtesseract and a command line program - tesseract. 
Tesseract was originally developed at Hewlett-Packard Laboratories Bristol UK and at Hewlett-Packard Co, Greeley Colorado USA between 1985 and 1994, with some more changes made in 1996 to port to Windows, and some C++izing in 1998. In 2005 Tesseract was open sourced by HP. From 2006 until November 2018 it was developed by Google.
Log: add lib name--tesseract

add tesseract

---

io.github.apk-editor-studio/linglong.yaml

APK Editor Studio is a powerful yet easy to use APK reverse-engineering tool
Log: add software name--apk-editor-studio

build: add apk-editor-studio

---

automake1.11/linglong.yaml

库中automake版本为1.16,pipewalker依赖于automake1.11

build: add automake1.11

---

io.github.snomcontrol/linglong.yaml

An application to control snom (D)3xx phones from the desktop
Log: add software name--snomcontrol

build: add snomcontrol

---

io.github.gpupad/linglong.yaml

A lightweight editor for GLSL shaders of all kinds and a fully-featured IDE for developing GPU based algorithms.
Log: add software name--gpupad

build: add gpupad

---

io.github.qtsconverter/linglong.yaml

A simple tool to convert qt translation file (ts) to other format (xlsx / csv) and vice versa.
log: add app --qtsconverter

build: add qtsconverter

---

io.github.Nanonote/linglong.yaml

Nanonote is a minimalist note taking application.
log: add app--Nanonote

build: add Nanonote

---

libgif7/linglong.yaml
libgif7/patches/disable-doc-patch.patch
libgif7/patches/fix-install-var-patch.patch

编译成功
因为源码里没有 `configure` 之类的文件，只有 `Makefile` 文件，其中 `PREFIX` 和 `LIBDIR` 是写死的，而且编译生成文档时会会下载文件，需要代理，所以使用补丁统一进行修改。
[https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=giflib-git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=giflib-git)
library for GIF images.
Log: add lib name--libgif7

build: add libgif7

---

io.github.QDriverStation/linglong.yaml

The QDriverStation is a cross-platform and open-source alternative to the FRC Driver Station.
Log: add software name--QDriverStation

build: add QDriverStation

---

io.github.laigter/linglong.yaml

Laigter is a tool that automatically generates maps for dynamic lighting effects in games. it allows normal, parallax, specular and occlusion map generation.
Log: add software name--laigter

build: add laigter

---

io.github.cvut.qtrvsim/linglong.yaml

build:qtrvsim
Finish build:qtrvsim for ll-builder.
Log:完成对qtrvsim的编译和运行

build:qtrvsim

---

kquickimageeditor/linglong.yaml

"KQuickImageEditor" is an image editor library based on Qt and KDE Frameworks, which provides functionality for image editing in Qt Quick applications.
log: add lib--kquickimageeditor

build: add kquickimageeditor

---

adwaita-qt/linglong.yaml

build lib: adwaita-qt, adwaita-qt for ll-builder
Log: 完成对adwaita-qt的编译。

build: add adwaita-qt

---

libsndfile/linglong.yaml

build lib:libsndfile 
Finish build lib:libsndfile for ll-builder
lib address : https://github.com/libsndfile/libsndfile.git
Complete the compilation of libsndfile

build lib:libsndfile

---

io.github.flameshot/linglong.yaml

flameshot, 一款截图标注工具。
git地址: https://github.com/flameshot-org/flameshot/tree/v12.1.0
Log: finish app flameshot.

build: add flameshot

---

io.github.sqlitebrowser/linglong.yaml

DB4S is for users and developers who want to create, search, and edit databases. DB4S uses a familiar spreadsheet-like interface, so complicated SQL commands do not have to be learned.
Log: add software name--sqlitebrowser

build: add sqlitebrowser

---

lxqt-build-tools/linglong.yaml

一个lib依赖库，依赖库libfm-qt依赖此依赖开发。
Log: finish lib lxqt-build-tools.

build: add lib lxqt-build-tools

---

io.github.MediaWriter/linglong.yaml

Fedora Media Writer是一个工具，可以帮助用户将Fedora图像放在他们的便携式驱动器上，如闪存盘。
Log: finish make MediaWriter.

build: add app MediaWriter

---

qtkeychain/linglong.yaml

build lib: qtKeychain, qtKeychain for desktop app
git url: https://github.com/frankosterfeld/qtkeychain
Log: finish lib qtKeychain

build: add qtKeychain

---

KolcorPicker/linglong.yaml

ColorPicker is a powerful screen color picker based on Qt's QColorDialog Class.

build: add ColorPicker

---

qtscxml/linglong.yaml

一个应用需要使用qt5的子模块scxml,而该子模块不存在。
Log: finish lib qtscxml.

build: add lib qtscxml

---

glfw/linglong.yaml

"Glfw" is a multi-platform library for OpenGL, OpenGL ES, Vulkan, window and input
log: add lib--glfw

build: add glfw

---

io.github.qmidictl/linglong.yaml

一款小工具，QmidiCtl是一个发送MIDI数据的MIDI远程控制器应用程序，通过网络，使用 UDP/IP 多播。
Log: finish qmidictl

build: add qmidictl

---

io.github.Cutepeaks/linglong.yaml

Supports AB1 and SCF 3.0 file formats. It has regular expression pattern finder and can export trace as SVG vector image.
Log: add software name--Cutepeaks

build: add Cutepeaks

---

io.github.rpan-studio/linglong.yaml

A software designed for capturing, compositing, encoding, recording, and streaming video content, efficiently.
Log: add software name--rpan-studio

build: add rpan-studio

---

portaudio/linglong.yaml

PortAudio is a cross-platform, open-source C language library for real-time audio input and output.
log: add lib--PortAudio

build: add portaudio

---

qxmpp/linglong.yaml

QXmpp is a cross-platform C++ XMPP client and server library. It is written in C++ and uses Qt framework.
log: add lib--qxmpp

build: add qxmpp

---

io.github.FeatherPad/linglong.yaml

FeatherPad (by Pedram Pourang, a.k.a. Tsu Jan tsujan2000@gmail.com) is a lightweight Qt plain-text editor for Linux.

build: add FeatherPad

---

io.github.Fractale/linglong.yaml

Modélisation 2D de la fractale de Von Koch avec différentes variantes.
Log: add software name--Fractale

build: add Fractale

---

io.github.qucs_s/linglong.yaml

provides a fancy graphical user interface for a number of popular circuit simulation engines.
Log: add software name--qucs_s

build: add qucs_s

---

io.github.Heimer/linglong.yaml

a desktop application for creating mind maps and other suitable diagrams. It's written in Qt and targeted for Linux and Windows.
Log: add software name--Heimer

build: add Heimer

---

crengine-ng/linglong.yaml

build: lib crengine_ng
Logs:success build lib crengine_ng for coolreader-ng

build: lib crengine_ng

---

cmake-shared/linglong.yaml

build: add lib cmake-shared

---

io.github.Flips/linglong.yaml

Flips: Floating IPS is a patcher for IPS and BPS files.
Log: finish app Flips.

build: add Flips

---

fluidsynth/linglong.yaml

一个依赖库，后续的qsynth应用需要使用。
Log: finish lib fluidsynth.

build: add lib fluidsynth

---

wxWidgets/linglong.yaml

实现应用treesheets时，缺少wxwidgets依赖包，此版本为3.2.3.
Log：finish lib build.

build: add lib wxWidgets

---

fltk/linglong.yaml

fltk是polished-map应用的依赖包。
git地址：https://github.com/fltk/fltk/tree/release-1.3.7。
Log: finish lib fltk.

build: add lib fltk

---

liblscp/linglong.yaml

qsampler应用的依赖构建库。
Log: finish lib liblscp.

build: add lib liblscp

---

io.github.qsynth/linglong.yaml

Qsynth 是一个使用 Qt Designer, 围绕 Qt 框架, 用 C++ 编写的 Fluidsynth GUI 前端应用程序。
Log: finish app qsynth.

build: add qsynth

---

io.github.htmldoc/linglong.yaml

HTMLDOC is a program that reads HTML and Markdown source files or web pages and generates corresponding EPUB, HTML, PostScript, or PDF files with an optional table of contents.

build: add htmldoc

---

inih/linglong.yaml

a lib for exiv2.    inih (INI Not Invented Here) is a simple .INI file parser written in C.

build: add lib inih

---

exiv2/linglong.yaml

a lib for qimgv.Exiv2 is a C++ library and a command-line utility to read, write, delete and modify Exif, IPTC, XMP and ICC image metadata.
我在这个文档那个里把inih依赖的source去掉了，本地编译成功了的。

build: add lib exiv2

---

io.github.falkon/linglong.yaml

Falkon is a KDE web browser. It uses QtWebEngine rendering engine.
log: add software--falkon

build: add falkon

---

io.github.sqreenshot/linglong.yaml

sqreenshot是一款截图小工具，支持任意大小的截图。
Log: finish app sqreenshot.

build: add sqreenshot

---

opencv3.4/linglong.yaml

OpenCV: Open Source Computer Vision Library
库里面那个是3.2,我看github上分支最新也只只有3.4.x

build: add opencv(3.4.x)

---

io.github.colorpick/linglong.yaml
io.github.colorpick/patches/fix-install-001.patch

Colorpick 是一个颜色选择器，通过让您选择背景和前景色并计算它们之间的对比度，可以轻松检查文本的可读性。
Log: finish app colorpick.
说明：install中对make生成的部分错误源码做了替换，否则install不下来app。

build: add colorpick

---

io.github.qimgv/linglong.yaml

Image viewer. Fast, easy to use. Optional video support.
目前暂不支持EXIV2、opencv功能（指把这里两个禁用）启用会出现运行时出现找不到库的错误。
但其实库是有的....
禁用之后功能可以正常使用

build: add qimgv

---

io.github.otter-browser/linglong.yaml

A browser controlled by the user, not vice-versa.
log: add software--otter-browser

build: add otter-browser

---

kcodecs/linglong.yaml

String encoding library
库里面有5.54的后面需要一个5.90

build: add lib kcodecs(5.90.0)

---

kirigami/linglong.yaml

QtQuick plugins to build user interfaces following the KDE Human Interface Guidelines.
log: add lib--kirigami

build: add kirigami

---

io.github.kontrast/linglong.yaml

Tool to check contrast for colors that allows verifying that your colors are correctly accessible.
log: add software--kontrast

build: add kontrast

---

io.github.dsched/linglong.yaml

Desktop Schedule
Log: add software name--dsched

build: add dsched

---

io.github.music-radar/linglong.yaml

Music Radar is music recognition application for Linux Desktop
Log: add software name--music-radar

build: add music-radar

---

io.github.alligator/linglong.yaml

Kirigami-based RSS reader.
log: add software--alligator

build: add alligator

---

io.github.voltrayke/linglong.yaml

Voltrayke 是一个基于 Qt 框架的音量控制应用程序，它提供了一些高级功能。
与传统桌面上的音量控制相比，Voltrayke 提供了更多的高级功能和自定义选项。它可以让用户更好地控制音量，并提供更好的用户体验。
Log: finish app voltrayke.

build: add voltrayke

---

io.github.2048-qt/linglong.yaml

Web based Popular 2048 game app implemented in Qt 5, uses QWebKit.
Log: add software name--2048-qt

build: add 2048-qt

---

io.github.spotify-qt/linglong.yaml

An unofficial Spotify client using Qt as a simpler, lighter alternative to the official client
Log: add software name--spotify-qt

build: add spotify-qt

---

io.github.pencil/linglong.yaml

Pencil2D 是一个简单、直观的工具，用于制作 2D 手绘动画。 Pencil2D 是开源且跨平台的。
Log: finish app pencil.

build: add pencil

---

io.github.noteshrink-qt/linglong.yaml

Convert scans of handwritten notes to beautiful, compact PDFs
Log: add software name--noteshrink-qt

build: add noteshrink-qt

---

io.github.GammaRay/linglong.yaml

GammaRay is a software introspection tool for Qt applications developed by KDAB. Leveraging the QObject introspection mechanism it allows you to observe and manipulate your application at runtime.
Log: add software name--GammaRay

build: add GammaRay

---

liblscp/linglong.yaml

上一次合入的liblscp,在使用过程中，发现lib与include并不在runtime文件夹中，而是做了一层嵌套进行了单独存储，导致使用沙箱无法读取对应依赖环境。

build: update liblscp

---

SDL_ttf/linglong.yaml

build: update sdl_ttf

---

io.github.xclicker/linglong.yaml
io.github.xclicker/patches/fix-001.patch

XClicker 是一款开源、易于使用、功能丰富、速度极快的 Autoclicker，适用于使用 x11 的 Linux 桌面。
Log: finish add xclicker.

build: add xclicker

---

io.github.qdirstat/linglong.yaml

QDirStat is a graphical application to show where your disk space has gone and to help you to clean it up.
Log: add software name--qdirstat

build: add qditstat

---

io.github.openPilotLog/linglong.yaml
io.github.openPilotLog/patches/0001-fix-desktop.patch

Welcome to openPilotLog, the free and open source airline pilot logbook application! You can find the latest release here. Please not that this is still an early testing version.
log: add software--openPilotLog

build add openPilotLog

---

io.github.QSerialTerminal/linglong.yaml
io.github.QSerialTerminal/patches/0001-install.patch

A simple, cross-platform serial port terminal application written with Qt/QML.
Log: add software name--QSerialTerminal

build: add QSerialTerminal

---

io.github.fdt-viewer/linglong.yaml

Flattened Device Tree Viewer
Log: add software name--fdt-viewer

build: add fdt-viewer

---

io.github.klatexformula/linglong.yaml

KLatexFormula is an easy-to-use graphical application for generating images (that you can drag and drop, copy and paste or save to disk) from LaTeX equations.
Log: add software name--klatexformula

build: add klatexformula

---

io.github.zeit/linglong.yaml

Qt frontend to crontab and at
Log: add software name--zeit

build: add zeit

---

io.github.qwiiload/linglong.yaml

Wii homebrew executable uploader
Log: add software name--qwiiload

build: add qwiiload

---

io.github.TexasSolver/linglong.yaml

A open sourced, extremely efficient Texas Hold'em and short deck solver.
Log: add software name--TexasSolver

build: add TexasSolver

---

io.github.Datapicker/linglong.yaml
io.github.Datapicker/patches/fix-001.patch

这种开源数字化软件将显示图形或地图的图像文件转换为数字。图像文件可以来自扫描仪、数码相机或屏幕截图。这些数字可以在屏幕上读取，并写入或复制到电子表格中。
Log: finish app Datapicker.

build: add Datapicker

---

io.github.qbr/linglong.yaml

Simple e-Book reader, written on C++ with Qt library.
Log: add software name--qbr
编译成功

build: add qbr

---

io.github.Projecteur/linglong.yaml

Linux/X11 application for the Logitech Spotlight device (and similar devices).
Log: add software name--Projecteur

build: add Projecteur

---

io.github.zeal/linglong.yaml

Zeal is a simple offline documentation browser inspired by Dash.
Log: add software name--zeal

build: add zeal

---

io.github.rssguard/linglong.yaml

RSS Guard is a simple RSS/ATOM feed reader for Windows, Linux, BSD, OS/2 or macOS which can work with RSS/ATOM/JSON/Sitemap feeds as well as many online feed services.
Log: add software name--rssguard

build: add rssguard

---

io.github.QTeletextMaker/linglong.yaml
io.github.QTeletextMaker/patches/0001-fix-install.patch

QTeletextMaker is a teletext page editor in development. It is written in C++ using the Qt 5 widget libraries, and released under the GNU General Public License v3.0
log: add software--QTeletextMaker

build: add QTeletextMaker

---

io.github.texstudio/linglong.yaml

TeXstudio is a fully featured LaTeX editor.
Our goal is to make writing LaTeX documents as easy and comfortable as possible.
Log: add software name--texstudio

build: add texstudio

---

io.github.iphelper/linglong.yaml

This simple tool displays the user's public-facing IPv4 address.
Log: add software name--iphelper

build: add iphelper

---

io.github.texworks/linglong.yaml

TeXworks is an environment for authoring TeX (LaTeX, ConTeXt, etc) documents, with a Unicode-based, TeX-aware editor, integrated PDF viewer, and a clean, simple interface accessible to casual and non-technical users.
Log: add software name--texworks

build: add texworks

---

io.github.CurrencyConv/linglong.yaml

CurrencyConv is a simple Application for Linux Desktop that converts currencies in seconds
Log: add software name--CurrencyConv

build: add CurrencyConv

---

io.github.puush-qt/linglong.yaml

A GUI frontend for puush on Linux. This will create a system tray icon and contains similar options to puush from Windows
Log: add software name--puush-qt

build: add puush-qt

---

io.github.duploq/linglong.yaml

DuploQ is a GUI frontend for Duplo duplicate finder console tool. Its goal is to find duplicates (i.e. copy-pasted parts of code) across several source files.
Log: add software name--duploq

build: add duploq

---

io.github.OpenTTD/linglong.yaml

OpenTTD is a transport simulation game based upon the popular game Transport Tycoon Deluxe, written by Chris Sawyer.
Log: add software name--OpenTTD

build: add OpenTTD

---

io.github.MedianXLOfflineTools/linglong.yaml
io.github.MedianXLOfflineTools/patches/add-desktop-file-patch.patch
io.github.MedianXLOfflineTools/patches/install-desktop-file-patch.patch

Character manager for Diablo 2 - Median XL mod.
Log: add software name--MedianXLOfflineTools
编译成功

build: add MedianXLOfflineTools

---

io.github.playdraughts/linglong.yaml
io.github.playdraughts/patches/0001-fix-install.patch

Play Draughts is a Linux human vs computer draughts game developed using C++ and Qt5.15.
log: add game--playdraughts

build: add playdraughts

---

io.github.LAN-Share/linglong.yaml
io.github.LAN-Share/patches/0001-install.patch

LAN Share is a cross platform local area network file transfer application, built using Qt GUI framework
Log: add software name--LAN-Share

build: add LAN-Share

---

io.github.wii-region-check/linglong.yaml
io.github.wii-region-check/patches/0001-install.patch

Wii tool for checking game region.
Log: add software name--wii-region-check

build: add wii-region-check

---

extra-cmake-modules/linglong.yaml

Finish build lib extra-cmake-modules for ll-build
Log: 完成更高版本（5.111.0）的extra-cmake-modules的编译

build: add lib extra-cmake-modules

---

io.github.TomatoTimer/linglong.yaml
io.github.TomatoTimer/patches/fix-001.patch

位于菜单栏中的简单番茄计时器,能根据用户设定来运行计时功能，方便提醒用户时间。
Log: finish app TomatoTimer.

build: add TomatoTimer

---

io.github.DoomRunner/linglong.yaml
io.github.DoomRunner/patches/fix-001.patch

Doom Runner 是另一个具有图形用户界面的常见 Doom 源端口（如 GZDoom、Zandronum、PrBoom 等）的启动器。它是用 C++ 和 Qt 编写的，其设计围绕各种多文件修改的预设理念（带有变异器的 Brutal Doom、带有 UDV 的 Project Brutality、Complex Doom Clusterfuck，...），以允许在它们之间一键切换并尽量减少重复性工作。
Log: finish app DoomRunner.

build: add DoomRunner

---

io.github.rektangles/linglong.yaml

Implementation of a Japanese puzzle game known as shikaku. A game for PinePhone (and for desktop).
log: add game--rektangles

build: add rektangles

---

io.github.iqpuzzle/linglong.yaml

iQPuzzle is a diverting I.Q. challenging pentomino puzzle. Pentominos are used as puzzle pieces and more than 300 different board shapes are available, which have to be filled with them.
log: add game--iqpuzzle

build: add iqpuzzle

---

io.github.stackandconquer/linglong.yaml

tackAndConquer is a challenging tower conquest board game inspired by Mixtour created by Dieter Stein who allows free copying and using the rule texts and graphics under CC license (BY-NC). Objective is to build a stack of stones with at least five stones and a stone with the players color on top.
log: add software--stackandconquer

build: add stackandconquer

---

io.github.Magic-Tower-Qt/linglong.yaml
io.github.Magic-Tower-Qt/patches/0001-install.patch

This is the C++(with Qt) version Magic-Tower game
Log: add software name--Magic-Tower-Qt

build: add Magic-Tower-Qt

---

io.github.fusepdf/linglong.yaml

FusePDF is a simple cross-platform application used for merging, splitting and exporting PDF pages and documents.
Log: add software name--fusepdf

build: add fusepdf

---

o.github.Heimdall/linglong.yaml
o.github.Heimdall/patches/0001-install.patch

Heimdall is a cross-platform open-source tool suite used to flash firmware (aka ROMs) onto Samsung mobile devices
Log: add software name--Heimdall

build: add Heimdall

---

io.github.chatterino2/linglong.yaml

Chatterino 2 is a chat client for Twitch.tv.
Logs: add app name--chatterino2

build: add app chatterino2

---

SDL_image/linglong.yaml

This is a simple library to load images of various formats as SDL surfaces.
log: add lib SDL_image

build: add lib SDL_image

---

io.github.qtask/linglong.yaml

QTask is an open-source Qt-based graphical user interface for managing tasks. It is based on Taskwarrior, a popular command-line organizer.
log: add software--qtask

build: add qtask

---

io.github.firebird/linglong.yaml

This project is currently the community TI-Nspire emulator, originally created by Goplat.
Log: add software name--firebird

build: add firebird

---

io.github.cassolette/linglong.yaml
io.github.cassolette/patches/0001-install.patch

Cassolette is a free and multi-platform utility software to help analysing and converting the encoding of text files.
Log: add software name--cassolette

build: add cassolette

---

io.github.HexEditor/linglong.yaml

Cross-platform Hex Editor
Log: add software name--HexEditor

build: add HexEditor

---

io.github.SVGStationPlanEditor/linglong.yaml
io.github.SVGStationPlanEditor/patches/0001-install.patch

A simple editor for railway station plan in SVG format
Log: add software name--SVGStationPlanEditor

build: add SVGStationPlanEditor

---

io.github.GitQlient/linglong.yaml
io.github.GitQlient/patches/0001-install.patch

GitQlient, pronounced as git+client (/gɪtˈklaɪənt/) is a multi-platform Git client originally forked from QGit.
Log: add software name--GitQlient

build: add GitQlient

---

io.github.ChineseChess/linglong.yaml
io.github.ChineseChess/patches/0001-install.patch

The Chinese chess online battle platform (including communication function) developed based on Qt5 realizes the function of chess game in a single or networked state
Log: add software name--ChineseChese

build: add ChineseChess

---

io.github.hmtimer/linglong.yaml
io.github.hmtimer/patches/fix-001.patch
io.github.hmtimer/patches/fix-002.patch

hmtimer 是一个适用于 Linux 和 Windows 的图形化关机计时器。 它使您可以在一段时间后关闭、关闭显示器、重新启动或播放声音。
Log: finish app hmtimer.

build: add hmtimer

---

io.github.cctools/linglong.yaml
io.github.cctools/patches/0001-install.patch

Editor and Tool suite for Chip's Challenge, Chip's Challenge 2, and Tile World
Log: add software name--cctools

build: add cctools

---

io.github.Disass/linglong.yaml
io.github.Disass/patches/0001-install.patch

It's mainly made for disassembly in mind, but if you found it comfortable to use for normal debugging purposes then go ahead!
Log: add software name--Disass

build: add Disass

---

io.github.ecalc/linglong.yaml
io.github.ecalc/patches/install.patch

This is a collection of handy calculators for electronics engineers.
log: add app--ecalc

build: add ecalc

---

io.github.NetSimulyzer/linglong.yaml
io.github.NetSimulyzer/patches/fix_install.patch

A flexible 3D visualizer for displaying, debugging, presenting, and understanding ns-3 scenarios.
Logs: add app name--NetSimulyzer

build: add app NetSimulyzer

---

io.github.giduba/linglong.yaml
io.github.giduba/patches/fix_install.patch

A lean, small, and simple Text Editor / Notepad Alternative for Linux.
Logs: add app name--giduba

build: add app giduba

---

io.github.BacklogManager-Qt/linglong.yaml
io.github.BacklogManager-Qt/patches/0001-install.patch

Qt application to help manage that pesky video game backlog.
Logs: add app name--BacklogManager-Qt

build: add app BacklogManager-Qt

---

io.github.ObjGui/linglong.yaml
io.github.ObjGui/patches/0001-install.patch

ObjGui uses objdump to disassemble executables, analyzes the data, and then provides an easy way to navigate through the disassembly.
Log: add software name--ObjGui

build: add ObjGui

---

io.github.LEDStripDesigner/linglong.yaml
io.github.LEDStripDesigner/patches/fix-001.patch

用于为 AVR Arduino ATMega328P 设计带动画的 LED 灯条 WS1228B 的软件。动画保存在 SD 卡上或通过 UART 发送到微处理器。 资源.
Log: finish app LEDStripDesigger.

build: add app LEDStripDesigner

---

io.github.cute-light-text-previewer/linglong.yaml
io.github.cute-light-text-previewer/patches/fix-001.patch

一个跨平台应用程序，可以立即打开和翻译大型文本文件。
Log: finish app cute-light-text-previewer.

build: add app cute-light-text-previewer

---

io.github.gltf-insight/linglong.yaml

gltf-insight is a C++11 based data insight tool for glTF 2.0 model.
Log: add software name--gltf-insight

build: add gltf-insight

---

io.github.qt_monkey/linglong.yaml
io.github.qt_monkey/patches/0001-install.patch

Qt Monkey is a tool to automate testing of Qt-based applications (widgets only). It automates creation/modification and running of the tests. Tests are written in Javascript (Qt supported dialect). 
Logs: add app name--qt_monkey

add Qt monkey

---

io.github.QOwnNotes/linglong.yaml

QOwnNotes is the open source notepad with markdown support and todo list manager for GNU/Linux, macOS and Windows, that works together with Nextcloud Notes and ownCloud Notes.
Logs: add app name--QOwnNotes

build: add app QOwnNotes

---

io.github.screengrab/linglong.yaml
io.github.screengrab/patches/fix-001.patch

用于创建屏幕截图的应用程序。 ScreenGrab 使用 Qt 框架，因此它独立于任何桌面环境。
Log: finish app screengrab.

build: add app screengrab

---

io.github.owoncontrol-qt/linglong.yaml
io.github.owoncontrol-qt/patches/0001-install.patch

Owon oscilloscope USB  in QT
Log: add software name--owoncontrol-qt

build: add owoncontrol-qt

---

io.github.SSopromatCAD/linglong.yaml
io.github.SSopromatCAD/patches/0001-install.patch

A computer-aided design system for material resistance problems.
Log: add software name--SSopromatCAD

build: add SSopromatCAD

---

io.github.qtmind/linglong.yaml
io.github.qtmind/patches/0001-install.patch

QtMind is a Mastermid game in Qt, with built in solver. Most of the major solving algorithms are integrated in QtMind.
Logs: add app name--qtmind

build: add app qtmind

---

io.github.SimpleConvert/linglong.yaml

Simple Convert is a small application in which you can convert multiple files to another file type at once using FFMPEG.
Log: add software name--SimpleConvert

build: add SimpleConvert

---

io.github.Quaternion/linglong.yaml

Quaternion is a cross-platform desktop IM client for the Matrix protocol. This file contains general information about application usage and settings. See BUILDING.md for building instructions.
Log: add software name--Quaternion

build: add Quaternion

---

io.github.qmarkdowntextedit/linglong.yaml
io.github.qmarkdowntextedit/patches/0001-install.patch

A C++ Qt QPlainTextEdit widget with markdown highlighting support and a lot of other extras.
Log: add software name--qmarkdowntextedit

build: add qmarkdowntextedit

---

io.github.MystiQ/linglong.yaml
io.github.MystiQ/patches/0001-install.patch

MystiQ is a GUI for FFmpeg, a powerful media converter. FFmpeg can read audio and video files in various formats and convert them into other formats.
Log: add software name--MystQ

build: add MystiQ

---

io.github.qxgedit/linglong.yaml

QXGEdit 是一个用于编辑 MIDI 系统专用文件的 Qt GUI
适用于 XG 设备（例如 Yamaha DB50XG）。
Log: finish app qxgedit.

build: add qxgedit

---

io.github.Steganographia/linglong.yaml
io.github.Steganographia/patches/0001-install.patch

A computer-aided design system for material resistance problems.
Log: add software name--Steganographia

build: add Steganographia

---

io.github.RepRaptor/linglong.yaml

Qt RepRap gcode sender/host controller aimed to be fast and minimalistic.
Log: add software name--RepRaptor![RepRaptor](https://github.com/linuxdeepin/linglong-hub/assets/147463620/859bb769-8dce-443f-9020-fb66743b918c)

build: add RepRaptor

---

io.github.LibrePCB/linglong.yaml

A powerful, innovative and intuitive EDA suite for everyone!
Logs: add app name--LibrePCB

build: add app LibrePCB

---

io.github.QLD/linglong.yaml
io.github.QLD/patches/0001-install.patch

A graphical tool to make the deploying of Qt quick applications on linux platform faster
Log: add software name--QLD

build: add QLD

---

autoconf/linglong.yaml

Autoconf is an extensible package of M4 macros that produce shell scripts to automatically configure software source code packages.
log: 添加lib autoconf

build: add autoconf

---

io.github.MrWriter/linglong.yaml
io.github.MrWriter/patches/fix-desktop-001.patch

一款写字板应用程序， 用 C++/Qt 编写，适用于 Linux / Windows / Mac。
Log: finish app MrWriter.

build: add MrWriter

---

io.github.hydratool/linglong.yaml
io.github.hydratool/patches/0001-fix-install.patch

This repository contains host software (Linux/Windows) for HydraBus with HydraFW firmware, a project to produce a low cost, open source multi-tool hardware for anyone interested in Learning/Developping/Debugging/Hacking/Penetration Testing for basic or advanced embedded hardware.
log: add software--hydratool

build: add hydratool

---

poppler-data/linglong.yaml

Data files for poppler to support uncommon encodings without xpdfrc.
Logs: add lib poppler-data

build: add lib poppler-data

---

io.github.CloudLogCatQt/linglong.yaml
io.github.CloudLogCatQt/patches/0001-install.patch

Qt app that can be compiled on Linux, Windows or Mac for providing CAT support for Cloudlog
Log: add software name--CloudLogCatQt

build: add CloudLogCatQt

---

io.github.Counter-Desktop/linglong.yaml
io.github.Counter-Desktop/patches/0001-fix-install.patch

Counter is desktop application that counts the number of characters and words in the text.
log: add software--Counter-Desktop

build: add Counter-Desktop

---

io.github.KNetStats/linglong.yaml

Simple network interface and statistics viewer
Log: add software name--KNetStats

build: add KNetStats

---

io.github.chmod-generator/linglong.yaml
io.github.chmod-generator/patches/0001-install.patch

This is a GUI for chmod and chown that I made when I was younger, while learning C++ and Qt.
Log: add software name--chmod-generator

build: add chmod-generator

---

io.github.uPDF2/linglong.yaml
io.github.uPDF2/patches/0001-fix-install.patch

This software is licensed under Gnu General Public License Version 3. Please look at the COPYING file for further details.
log: add software--uPDF2

build:add uPDF2

---

io.github.qt5-action-editor/linglong.yaml
io.github.qt5-action-editor/patches/0001-fix-install.patch

A port of qq14-actioneditor from Qt Quarterly to Qt5.
log: add software--qt5-action-editor

build: add qt5-action-editor

---

io.github.FractalCryptGUI/linglong.yaml
io.github.FractalCryptGUI/patches/0001-install.patch

Free cross-platform deniable encryption cryptoarchiver
Log: add software name--FractalCryptGUI

build: add FractalCryptGUI

---

io.github.NotepadNext/linglong.yaml

Notepad Next is yet another text and source code editor.
log: add app--NotepadNext

build: add NotepadNext

---

io.github.fitbit-activities-chart/linglong.yaml
io.github.fitbit-activities-chart/patches/fix-001.patch

Fitbit活动图表，将csv文件导入，可以展示对应的图表。
Log: finish app fitbit-activities-chart.

build: add app fitbit-activities-chart

---

io.github.git-chart-drawer/linglong.yaml

使用QT和QTCHARTS从您的GIT存储库中绘制图表.
Log: finish app git-chart-drawer.

build: add app git-chart-drawer

---

io.github.qiniu_Qt/linglong.yaml
io.github.qiniu_Qt/patches/install.patch

The use of cloud and map bed can greatly simplify the chain of access to the process, the picture or file drag and drop to the“Cloud and map bed” can be triggered!
log: add app--qiniu_Qt

build: add qiniu_Qt

---

io.github.HJ-Editor/linglong.yaml
io.github.HJ-Editor/patches/install.patch

A simple C + + IDE with Lenovo, code highlighting, compile and run, and more
log: add app--HJ-Editor

build: add HJ-Editor

---

io.github.qawno/linglong.yaml
io.github.qawno/patches/install.patch

Qawno is a simple cross-platform Pawn editor with syntax highlighting and script compilation support.
log: add app--qawno

build: add qawno

---

doxygen/linglong.yaml

Doxygen is the de facto standard tool for generating documentation from annotated C++ sources
log: add lib

build: add lib doxygen

---

sassc/linglong.yaml

A libsass command line driver.
Logs: add lib sassc

build: add lib sassc

---

libxmu/linglong.yaml

This library contains miscellaneous utilities and is not part of the Xlib standard.
log: add lib

build: add libxmu

---

io.github.speedcrunch/linglong.yaml

SpeedCrunch是高精度的科学计算器。它具有语法高的可滚动显示屏，设计为通过键盘充分使用。
Log: finish app speedcrunch.

build: add app speedcrunch

---

io.github.HTYPaint_Qt/linglong.yaml
io.github.HTYPaint_Qt/patches/0001-install.patch

Finish build HTYPaint_Qt for ll-build
Log: 完成App:HTYPaint_Qt的编译

build: add HTYPaint_Qt

---

io.github.windows-notepad/linglong.yaml
io.github.windows-notepad/patches/0001-install.patch

通过Qt实现windows下记事本下的所有功能，是用户在linux等平台上获得一致的操作体验
Log: add software name--notepad

build: add windows-notepad

---

org.xfce.gigolo/linglong.yaml

Gigolo is a frontend to easily manage connections to local and remote filesystems using GIO/GVfs.
log: add sofware--gigole

build: add gigole

---

io.github.nedit-ng/linglong.yaml
io.github.nedit-ng/patches/0001-install.patch

Finish build nedit-ng for ll-build
Log: 完成App:nedit-ng的编译

build: add nedit-ng

---

io.github.USBCAN-GUI/linglong.yaml
io.github.USBCAN-GUI/patches/0001-install.patch

This is a Linux-based GUI (shown below) to interact with the USB-CAN analyzer in order to send and receive packets over a CAN bus.
Log: add software name--USBCAN-GUI

build: add USBCAN-GUI

---

glm/linglong.yaml

OpenGL Mathematics (GLM) is a header only C++ mathematics library for graphics software based on the OpenGL Shading Language (GLSL) specifications.
log: add lib

build: add lig glm

---

io.github.rtf-editor/linglong.yaml
io.github.rtf-editor/patches/add-desktop-file-patch.patch
io.github.rtf-editor/patches/install-desktop-file-patch.patch

build: add rtf-editor

---

io.github.usb2sniffer-qt/linglong.yaml
io.github.usb2sniffer-qt/patches/install-desktop.patch

finish build usb2sniffer-qt for ll-build
Log: 完成usb2sniffer-qt的编译

build: add usb2sniffer-qt

---

io.github.Simple-Text-Editor/linglong.yaml
io.github.Simple-Text-Editor/patches/0001-install.patch

Simple-Text-Editor, as the name suggests, is a simple text editor made with the Qt framework.
Logs: add app name--Simple-Text-Editor

build: add app Simple-Text-Editor

---

io.github.MimeDetector/linglong.yaml
io.github.MimeDetector/patches/0001-install.patch

As the name suggests, MimeDetector is a simple program for recognizing the MIME type of files.
Logs: add app name--MimeDetector

build: add app MimeDetector

---

com.debian.ipqalc/linglong.yaml
com.debian.ipqalc/patches/fix_001.patch

新增应用ipqalc,用于 IP 地址计算的小型实用程序，包括广播和网络地址以及 Cisco 通配符掩码

build: add app ipqalc

---

io.github.qcalcfilehash/linglong.yaml
io.github.qcalcfilehash/patches/fix_001.patch

新增应用qcalcfilehash,计算验证hash的图形应用程序

build: add app qcalcfilehash

---

io.github.KeyboardVisualizer/linglong.yaml

Finish build KeyboardVisualizer for ll-build
Log: 完成KeyboardVisualizer的编译

build: add KeyboardVisualizer

---

io.github.picta-dl-gui/linglong.yaml

Picta Downloader GUI
Log: add software name--picta-dl-gui

build: add picta-dl-gui

---

io.github.screenshotgun/linglong.yaml

Open cross-platform screenshoter with cloud support and server part
Log: add software name--screenshotgun

build: add screenshotgun

---

com.gitlab.Abstract-Games/linglong.yaml

build: add Abstract-Games

---

io.github.tagberry/linglong.yaml

Finish build tagberry for ll-build
Log: 完成tagberry的编译

build: add tagberry

---

io.github.lovi/linglong.yaml
io.github.lovi/patches/fix-001.patch

Lovi 是一个日志文件查看器。 Lovi 的工作原理是将日志文件拆分为列，并根据用户定义的突出显示对某些行或单元格进行着色。
Log: finish app lovi.

build: add app lovi

---

ftgl/linglong.yaml

FTGL is a free open source library to enable developers to use arbitrary fonts in their OpenGL (www.opengl.org) applications.
Logs: add lib ftgl

build: add lib ftgl

---

karchive/linglong.yaml

KArchive provides classes for easy reading, creation and manipulation of "archive" formats like ZIP and TAR.
log: add lib

build: add lib karchive

---

graphene/linglong.yaml

A thin layer of types for graphic libraries.
Logs: add lib graphene

build: add lib graphene

---

ngspice/linglong.yaml

Ngspice is a mixed-level/mixed-signal circuit simulator.
log: add lib

build: add lib ngspice

---

appstream-glib/linglong.yaml

Provides GObjects and helper methods to read and write AppStream metadata.
Logs: add lib appstream-glib

build: add lib appstream-glib

---

tagparser/linglong.yaml

C++ library for reading and writing MP4/M4A/AAC (iTunes), ID3, Vorbis, Opus, FLAC and Matroska tags.
Logs: add lib tagparser

build: add lib tagparser

---

opus/linglong.yaml

Opus is a codec for interactive speech and audio transmission over the Internet.
log: add lib

build: add opus

---

libxmp/linglong.yaml

Libxmp is a library that renders module files to PCM data.
log: add lib

build: add libxmp

---

woff2/linglong.yaml

The primary purpose of the WOFF2 format is to efficiently package fonts linked to Web documents by means of CSS @font-face rules.
log: add lib

build: add woff2

---

io.github.edb-debugger/linglong.yaml
io.github.edb-debugger/patches/fix_install.patch

edb is a cross-platform AArch32/x86/x86-64 debugger.
Logs: add app name--edb-debugger
需要设置 `plugin directory` 为 `/opt/apps/io.github.edb-debugger/files/lib/x86_64-linux-gnu/edb/`

build: add app edb-debugger

---

ogg/linglong.yaml

Ogg project codecs use the Ogg bitstream format to arrange the raw.
log: add lib--ogg

build: lib ogg

---

io.github.kapow/linglong.yaml

Kapow 是一款打卡钟程序，旨在轻松记录您的时间，无论您正在从事一个项目还是多个项目。只需使用以下命令即可上下班打卡 开始/停止按钮。如果您在工作时间内犯了错误，您可以返回并通过双击相关会话来编辑任何条目。
Log: finish app kapow.

build: add app kapow

---

io.github.gottet/linglong.yaml

Gottet 是俄罗斯方块的克隆版。碎片从顶部落下游戏区域的位置，您可以水平移动它们以及旋转它们在他们到达游乐区底部之前。目标是打造完整 线片，然后将其移除。当堆栈到达时游戏结束的棋子到达游戏区域的顶部。
Log: finish app gottet.

build: add app gottet

---

io.github.connectagram/linglong.yaml

Connectagram 是一款单词解读游戏。由几位成员组成连接在一起的乱序单词。您可以选择长度单词、单词数量以及单词排列方式 游戏为您遇到困难时提供提示选项，并且具有在线单词查找功能，可获取每个单词的定义来自维基词典。您当前的进度会自动保存。
Log: finsih app connectagram.

build: add app connectagram

---

io.github.novprog/linglong.yaml

NovProg 是一个用于绘制小说写作进度的工具。您输入您的wordcount 会更新一个图表，显示您的进度制成。它还会显示您完成每日目标的进度以及您的目标 总目标。将鼠标悬停在图表中的条形上将显示一个工具提示一天的字数。
Log: finish app novprog.

build: add app novprog

---

io.github.hexalate/linglong.yaml

Hexalate 是一款配色游戏。游戏的目标是旋转和定位圆圈，使每条接触线的颜色相匹配。你通过右键单击来旋转圆圈，并通过拖动来移动圆圈。游戏存储各轮运行中圆圈的位置和旋转。
Log: finsih app hexalate.

build: add app hexalate

---

io.github.PianoBooster/linglong.yaml

A MIDI file player/game that displays the musical notes and teaches you how to play the piano.
Logs: add app name--PianoBooster

build: add app PianoBooster

---

io.github.OpenRGB/linglong.yaml
io.github.OpenRGB/patches/0001-install.patch

Open source RGB lighting control that doesn't depend on manufacturer software. Supports Windows, Linux, MacOS.
Log: add software name--OpenRGB

build: add OpenRGB

---

io.github.jmbde-QT/linglong.yaml

A program to collect the resources of a company in a database. These are computers, printers, phones and more.
Logs: add app name--jmbde-QT

build: add app jmbde-QT

---

io.github.olive/linglong.yaml

Free open-source non-linear video editor.
Logs: add app name--olive

build: add app olive

---

io.github.DeepTags/linglong.yaml
io.github.DeepTags/patches/0001-install.patch

DeepTags is a markdown notes manager with support for nested tags
Log: add software name--DeepTags

build: add DeepTags

---

io.github.Attendance/linglong.yaml

the attendance tracking program for robotics
Log: add software name--Attendance

build: add Attendance

---

io.github.sequencer64/linglong.yaml
io.github.sequencer64/patches/fix_desktop.patch

Log: 完成App：sequencer64的编译
修复使用自带desktop文件
版本号已升级

build: add sequencer64

---

io.github.Drawing-Board-Sigma/linglong.yaml
io.github.Drawing-Board-Sigma/patches/0001-1.patch

Finish build Drawing-Board-Sigma for ll-build
Log: 完成Drawing-Board-Sigma的编译

build: add Drawing-Board-Sigma

---

Hamlib/linglong.yaml

Hamlib,一个依赖库，应用klog依赖其进行打包编译。
Log: finish lib Hamlib.

build: lib Hamlib

---

io.github.fantascene-dynamic-wallpaper/linglong.yaml

Managed animated wallpaper based on X11 under Linux.
log: add app

build: add fantascene-dynamic-wallpaper

---

io.github.CasterSoundboard/linglong.yaml

Finish build CasterSoundboard for ll-build
Log: 完成CasterSoundboard的编译

build: add CasterSoundboard

---

io.github.seq66/linglong.yaml
io.github.seq66/patches/fix-desktop.patch

Log: 完成App：seq66的编译。
更新了版本号。
优化使用了自带desktop文件。

build: add seq66

---

io.github.upsm/linglong.yaml

Qt-based ups monitor (front-end for upsc from Network UPS Tools)
Log: add software name--upsm

build: add upsm

---

io.github.e2-sat-editor/linglong.yaml

Satellite channel lists editor with tabbed nav 📡 for Enigma2, Neutrino, Lamedb, dreambox lists
Log: add software name--e2-sat-editor

build: add e2-sat-editor

---

io.github.loganalyzer/linglong.yaml

LogAnalyzer is a tool that helps you to analyze your log files by reducing the content with patterns you define.
Logs: add app name--loganalyzer

build: add app loganalyzer

---

io.github.FastQt/linglong.yaml
io.github.FastQt/patches/0001-install.patch

FastQC port to Qt5: A quality control tool for high throughput sequence data.
Log: add software name--FastQt

build: add FastQt

---

io.github.embedded-ide/linglong.yaml

IDE for C embedded development centered on bare-metal ARM systems.
Logs: add app name--embedded-ide

build: add app embedded-ide

---

io.github.gtest-runner/linglong.yaml
io.github.gtest-runner/patches/fix_build.patch

A cross-platform, Qt5 based Graphical User Interface for Google Test unit tests.
Logs: add app name--gtest-runner

build: add app gtest-runner

---

io.github.Project_LemonLime/linglong.yaml

为了 OI 比赛而生的基于 Lemon + LemonPlus 的轻量评测系统 | 三大桌面系统支持.
Logs: add app name--Project_LemonLime

build: add app Project_LemonLime

---

io.github.zNotes/linglong.yaml
io.github.zNotes/patches/0001-install.patch

zNotes is a lightweight cross-platform application for notes management.
Log: add software name--zNotes

build: add zNotes

---

fio/linglong.yaml

Flexible I/O Tester.
`configure` 不支持 `libdir` 参数
Logs: add lib fio

build: add lib fio

---

io.github.pdfquirk/linglong.yaml

Creating PDFs from images or scanner made easy.
Log: add software name--pdfquirk

build: add pdfquirk

---

io.github.ser-player/linglong.yaml
io.github.ser-player/patches/0001-install.patch

A simple video player for playing SER files used for solar, lunar and planetary astronomy-imaging.
Log: add software name--ser-player

build: add ser-player

---

io.github.color-generator/linglong.yaml
io.github.color-generator/patches/0001-install.patch

An application that generates color palettes similar to ColorBrewer but algorithmically using intuitive parameters.
Log: add software name--color-generator

build: add color-generator

---

io.github.Forserino/linglong.yaml

Chat client for twitch.tv. See releases for download. Only nightlies are supported.
Log: add software name--Forserino

build: add Forserino

---

io.github.brickstore/linglong.yaml

An offline BrickLink inventory management tool.
Log: add software name--brickstore

build: add brickstore

---

io.github.coolreader/linglong.yaml

Official site of CoolReader project. Sourceforge repository is obsolete.
Log: add software name--coolreader

build: add coolreader

---

io.github.qmidinet/linglong.yaml

QmidiNet - A MIDI Network Gateway via UDP/IP Multicast
Log: add software name--qmidinet

build: add qmidinet

---

io.github.subtivals/linglong.yaml

Subtivals is a tool to project subtitles under a movie in festivals, specialy targeted at the hard of hearing community.
Log: add software name--subtivals

build: add subtivals

---

io.github.basic_numerical_methods/linglong.yaml
io.github.basic_numerical_methods/patches/0001-install.patch

A Qt application for basic numerical methods.
Log: add software name--basic_numerical_methods

build: add basic_numerical_methods

---

io.github.water_hammer_simulation/linglong.yaml
io.github.water_hammer_simulation/patches/0001-install.patch

A Qt application for water hammer simulation.
Log: add software name--water_hammer_simulation

build: add water_hammer_simulation

---

io.github.ArrowDL/linglong.yaml
io.github.ArrowDL/patches/0001-install.patch
io.github.ArrowDL/patches/0002-install.patch

ArrowDL (Arrow Downloader) is a download manager for Windows, MacOS and Linux
Log: add software name--ArrowDL

build: add ArrowDL

---

io.github.rssguard-inkbox/linglong.yaml

Feed reader which supports RSS/ATOM/JSON and many web-based feed services.
Log: add software name--rssguard-inkbox

build: add rssguard-inkbox

---

io.github.frsky_sport_tool/linglong.yaml
io.github.frsky_sport_tool/patches/0001-install.patch

Open-Source, Multi-Platform Frsky Sport Tool Suite for firmware programming, device configuration, and data monitoring of Frsky RC Receivers and Telemetry devices.
Log: add software name--frsky_sport_tool

build: add frsky_sport_tool

---

io.github.lithomaker/linglong.yaml
io.github.lithomaker/patches/0001-install.patch

Creates 3D lithophanes from image files, exports them to stl files, ready for slicing and 3D printing.
Log: add software name--lithomaker

build: add lithomaker

---

io.github.Intan-RHX/linglong.yaml
io.github.Intan-RHX/patches/0001-install.patch
io.github.Intan-RHX/patches/0002-install.patch

Intan RHX is free, powerful data acquisition software that displays and records electrophysiological signals from any Intan RHD or RHS system using an RHD USB interface board
Log: add software name--Intan-RHX

build: add Intan-RHX

---

io.github.qView-minimal/linglong.yaml
io.github.qView-minimal/patches/0001-install.patch

Practical and minimal image viewer
Log: add software name--qView-minimal

build: add qView-minimal

---

io.github.nitrokey-app/linglong.yaml

Nitrokey's Application (Win, Linux, Mac).
Logs: add app name--nitrokey-app

build: add app nitrokey-app

---

io.github.dankerino/linglong.yaml

Chat client for twitch.tv. See releases for download. Only nightlies are supported.
Log: add software name--dankerino

build: add dankerino

---

io.github.qfm1000/linglong.yaml

Philips FM1000 EEPROM channels and configuration parameters editor.
Logs: add app name--qfm1000

build: add app qfm1000

---

io.github.fingerboard/linglong.yaml

A fprintd based fingerprint GUI for Linux.
Logs: add app name--fingerboard

build: add app fingerboard

---

io.github.goat/linglong.yaml
io.github.goat/patches/fix_install.patch

Database frontend written in QT5 using widgets. At some point it should provide an alternative to tools like mysql workbench and pgadmin.
Logs: add app name--goat

build: add app goat

---

io.github.zint/linglong.yaml
io.github.zint/patches/0001-install.patch
io.github.zint/patches/0002-install.patch

Zint is a suite of programs to allow easy encoding of data in any of the wide range of public domain barcode standards and to allow integration ofthis capability into your own programs.
Log: add software name--zint

build: add zint

---

io.github.vnote/linglong.yaml

A pleasant note-taking platform.
Log: add software name--vnote

build: add vnote

---

io.github.Treinamento_SQL/linglong.yaml

Official home of the DB Browser for SQLite (DB4S) project
Log: add software name--Treinamento_SQL

build: add Treinamento_SQL

---

io.github.stpa-documentation-tool/linglong.yaml
io.github.stpa-documentation-tool/patches/0001-install.patch

This tool aims to organize STPA analysis results in a tree format, and then produce analysis documentation automatically
Log: add software name--stpa-documentation-tool

build: add stpa-documentation-tool

---

io.github.artmoo/linglong.yaml
io.github.artmoo/patches/fix_desktop.patch

A telnet/websocket Multi-user Object Orientated (MOO) server for creating text-only art projects and virtual worlds.
Logs: add app name--artmoo

build: add app artmoo

---

io.github.PKGBUILD-Assistant/linglong.yaml
io.github.PKGBUILD-Assistant/patches/fix_install.patch

An auxiliary tool for writing PKGBUILD files written in Qt5
Logs: add app name--PKGBUILD-Assistant

build: add app PKGBUILD-Assistant

---

io.github.DiskImagery64/linglong.yaml
io.github.DiskImagery64/patches/fix_install.patch

A portable drag & drop D64 Disk Image Editor.
Logs: add app name--DiskImagery64

build: add app DiskImagery64

---

io.github.coretime/linglong.yaml
io.github.coretime/patches/0001-install.patch

CoreTime is a time related task app
Log: add software name--coretime

build: add coretime

---

io.github.QMidiPlayer/linglong.yaml
io.github.QMidiPlayer/patches/0001-install.patch

A cross-platform midi file player based on libfluidsynth and Qt.
Log: add software name--QMidiPlayer

build: add QMidiPlayer

---

io.github.CPU-X/linglong.yaml

CPU-X is a Free software that gathers information on CPU, motherboard and more
Log: add software name--CPU-X

build: add CPU-X

---

io.github.delaycut/linglong.yaml
io.github.delaycut/patches/fix_install.patch

cuts and corrects delay in ac3 and dts files.
Logs: add app name--delaycut

build: add app delaycut

---

io.github.plug/linglong.yaml

Software for Fender Mustang Amps.
Logs: add app name--plug

build: add app plug

---

io.github.scantailor-advanced/linglong.yaml

ScanTailor Advanced is the version that merges the features of the ScanTailor Featured and ScanTailor Enhanced versions, brings new ones and fixes.
Log: add software name--scantailor-advanced

build: add scantailor-advanced

---

io.github.endless-sky-editor/linglong.yaml
io.github.endless-sky-editor/patches/0001-install.patch

Map editor for the Endless Sky universe.
Log: add software name--endless-sky-editor

build: add endless-sky-editor

---

io.github.CopyQ/linglong.yaml

Clipboard manager with advanced features
Log: add software name--CopyQ

build: add CopyQ

---

io.github.Cockatrice/linglong.yaml

A cross-platform virtual tabletop for multiplayer card games
Log: add software name--Cockatrice

build: add Cockatrice

---

io.github.xca/linglong.yaml

X Certificate and Key management
Log: add software name--xca

build: add xca

---

io.github.flacon/linglong.yaml

Audio File Encoder. Extracts audio tracks from an audio CD image to separate tracks.
Log: add software name--flacon

build: add flacon

---

io.github.quassel/linglong.yaml

Quassel IRC: Chat comfortably. Everywhere.
Log: add software name--quassel

build: add quassel

---

io.github.qgo/linglong.yaml
io.github.qgo/patches/0001-install.patch

qGo is a Go Client (IGS, WING, LGS, WBaduk/CyberORO, Tygem, Tom, and eWeiqi) based on Qt 5.
Log: add software name--qgo

build: add qgo

---

io.github.DoomRunnerOA/linglong.yaml
io.github.DoomRunnerOA/patches/0001-install.patch

Preset-oriented graphical launcher of various ported Doom engines (an alternative to ZDL)
Log: add software name--DoomRunnerOA

build: add DoomRunnerOA

---

io.github.gta5view/linglong.yaml

Open Source Snapmatic and Savegame viewer/editor for GTA V
Log: add software name--gta5view

build: add gta5view

---

io.github.LibreCAD/linglong.yaml
io.github.LibreCAD/patches/0001-install.patch
io.github.LibreCAD/patches/0002-install.patch
io.github.LibreCAD/patches/0003-install.patch

LibreCAD is a cross-platform 2D CAD program written in C++17 using the Qt framework.
Log: add software name--LibreCAD

build: add LibreCAD

---

io.github.pineapple-chapter-tool/linglong.yaml
io.github.pineapple-chapter-tool/patches/0001-install.patch

Tool for adding chapter markers to audio files.
Log: add software name--pineapple-chapter-tool

build: add pineapple-chapter-tool

---

io.github.SimulIDE/linglong.yaml
io.github.SimulIDE/patches/0001-install.patch

SimulIDE is a simple real-time electronic circuit simulator
Log: add software name--SimulIDE

build: add SimulIDE

---

io.github.VMPK/linglong.yaml

Virtual MIDI Piano Keyboard
Log: add software name--VMPK

build: add VMPK

---

io.github.tipp10/linglong.yaml

Tipp10 is a free touch typing tutor for your browser and for user.
Log: add software name--tipp10

build: add tipp10

---

io.github.ellipticcurve/linglong.yaml

Play and exeriment with elliptic curves and their group law.
Log: add software name--ellipticcurve

build: add ellipticcurve

---

io.github.countdown/linglong.yaml
io.github.countdown/patches/0001-install.patch

A simple count-down clock for exams etc.
Log: add software name--countdown

build: add countdown

---

io.github.crwx-ng/linglong.yaml
io.github.crwx-ng/patches/0001-install.patch

crwx-ng - cross-platform open source e-book reader
Log: add software name--crwx-ng

build: add crwx-ng

---

io.github.openbabel/linglong.yaml
io.github.openbabel/patches/0001-install.patch

Open Babel is a chemical toolbox designed to speak the many languages of chemical data.
Log: add software name--openbabel

build: add openbabel

---

io.github.kochmorse/linglong.yaml

A simple morse tutor using the Koch method.
Log: add software name--kochmorse

build: add kochmorse

---

io.github.basic256/linglong.yaml
io.github.basic256/patches/0001-install.patch

BASIC-256 is an easy to use version of BASIC designed to teach anybody (especially middle and high-school students) the basics of computer programming.
Log: add software name--basic256

build: add basic256

---

io.github.inventory-files/linglong.yaml
io.github.inventory-files/patches/fix_desktop.patch
io.github.inventory-files/patches/fix_install.patch

Program for inventory files on your computer (for linux).
先使用 insert 按钮加入一个目录，然后才能使用 scan 按钮检索，然后在 files 页面会有检索的结果。
Logs: add app name--inventory-files

build: add app inventory-files

---

io.github.Penguin-Subtitle-Player/linglong.yaml

An open-source, cross-platform standalone subtitle player
Log: add software name--Penguin-Subtitle-Player

build: add Penguin-Subtitle-Player

---

io.github.q5Go/linglong.yaml
io.github.q5Go/patches/0001-install.patch

A tool for Go players: SGF editor, analysis tool, game database and pattern search tool, IGS client
Log: add software name--q5Go

build: add q5Go

---

io.github.elokab-adhan/linglong.yaml
io.github.elokab-adhan/patches/0001-install.patch

System tray prayer time built in Qt.
Log: add software name--elokab-adhan

build: add elokab-adhan

---

io.github.OpenKJ/linglong.yaml
io.github.OpenKJ/patches/0001-install.patch

Open source karaoke show hosting software.
Log: add software name--OpenKJ

build: add OpenKJ

---

io.github.KVIrc/linglong.yaml

The KVIrc IRC Client
Log: add software name--KVIrc

build: add KVIrc

---

io.github.NatronPluginManager/linglong.yaml

Natron Plug-in Manager.
需要等待插件元文件的下载。
Logs: add app name--NatronPluginManager

build: add app NatronPluginManager

---

io.github.apkstudio/linglong.yaml
io.github.apkstudio/patches/0001-install.patch

Open-source, cross platform Qt based IDE for reverse-engineering Android application packages.
Log: add software name--apkstudio

build: add apkstudio

---

io.github.musiqt/linglong.yaml

Simple and cross-platform music player.
Log: add software name--musiqt

build: add musiqt

---

io.github.mupen64plus-qt/linglong.yaml
io.github.mupen64plus-qt/patches/0001-install.patch

A customizable launcher for Mupen64Plus
Log: add software name--mupen64plus-qt

build: add mupen64plus-qt

---

io.github.neonbtl-qt/linglong.yaml
io.github.neonbtl-qt/patches/0001-install.patch

Emulator for Soyuz-Neon PK-11/16
Log: add software name--neonbtl-qt

build: add neonbtl-qt

---

io.github.QLogo/linglong.yaml
io.github.QLogo/patches/0001-install.patch

QLogo is a rewrite of the UCBLogo language and user interface with UCB compatibility.
Log: add software name--QLogo

build: add QLogo

---

io.github.qactus/linglong.yaml

A Qt-based Open Build Service client
Log: add software name--qactus

build: add qactus

---

io.github.ClownMapEd/linglong.yaml

Sonic the Hedgehog sprite editor, portable clone of Xenowhirl's SonMapEd.
Log: add software name--ClownMapEd

build: add ClownMapEd

---

io.github.gpsbabel/linglong.yaml
io.github.gpsbabel/patches/0001-install.patch

GPSBabel: convert, manipulate, and transfer data from GPS programs or GPS receivers.
Log: add software name--gpsbabel

build: add gpsbabel

---

io.github.helloworld-gui/linglong.yaml
io.github.helloworld-gui/patches/0001-install.patch

Cross-platform GUI version of Hello World. This is useful for checking the operation of the GUI.
Log: add software name--helloworld-gui

build: add helloworld-gui

---

io.github.qpiskvork/linglong.yaml
io.github.qpiskvork/patches/0001-install.patch

Another gomoku or renju manager adapting to Windows and Linux systems.
Log: add software name--qpiskvork

build: add qpiskvork

---

io.github.vchar64/linglong.yaml
io.github.vchar64/patches/0001-install.patch

editor for the Commodore 64
Log: add software name--vchar64

build: add vchar64

---

io.github.ImGuiFontStudio/linglong.yaml
io.github.ImGuiFontStudio/patches/0001-fix-code.patch
io.github.ImGuiFontStudio/patches/0001-fix-install.patch

ImGuiFontStudio is a tool for Subset font and extract glyph names for use embbeded or not in a software, especially for use with ImGui for embedded way.

build: add ImGuiFontStudio

---

io.github.QHexEdit/linglong.yaml
io.github.QHexEdit/patches/0001-fix-desktop.patch

QHexEdit is a hex editor widget written in C++ for the Qt (Qt4, Qt5) framework. It is a simple editor for binary data, just like QPlainTextEdit is for text data.

build: add QHexEdit

---

io.github.GitlHEVCAnalyzer/linglong.yaml
io.github.GitlHEVCAnalyzer/patches/0001-install.patch

Gitl HEVC/H.265 Analyzer based on Qt. Custom filters supported.
Log: add software name--GitlHEVCAnalyzer

build: add GitlHEVCAnalyzer

---

io.github.SdPlayer/linglong.yaml
io.github.SdPlayer/patches/0001-install.patch

Music player for square dance tape groups
Log: add software name--SdPlayer

build: add SdPlayer

---

io.github.Proxmark3GUI/linglong.yaml
io.github.Proxmark3GUI/patches/0001-fix-desktop.patch

A cross-platform GUI for Proxmark3/Proxmark3 Iceman fork client
log: add a software but no desktop icon

build: add Proxmark3GUI

---

io.github.caj2pdf-qt/linglong.yaml
io.github.caj2pdf-qt/patches/0001-fix-desktop.patch

build: add caj2pdf

---

io.github.Tasker/linglong.yaml
io.github.Tasker/patches/fix_install.patch

A commitment tracker desktop app that tracks the progress of your tasks with mouse, keyboard and audio hooks.
Logs: add app name--Tasker

build: add app Tasker

---

io.github.opulus/linglong.yaml

Simple Petri net editor and simulator
Log: add software name--opulus

build: add opulus

---

io.github.EmuDiscer/linglong.yaml
io.github.EmuDiscer/patches/0001-install.patch

EmuDiscer recognizes which system the game is made for, and lauches the right emulator.
Log: add software name--EmuDiscer

build: add EmuDiscer

---

io.github.LANDrop-Pro/linglong.yaml

Drop any files to any devices on your LAN even on WAN.
Log: add software name--LANDrop-Pro

build: add LANDrop-Pro

---

io.github.faustworks/linglong.yaml
io.github.faustworks/patches/0001-install.patch

FaustWorks is an IDE (Integrated Development Environment) for the Faust dsp programming language.
Log: add software name--faustworks

build: add faustworks

---

io.github.small-scope-qt/linglong.yaml
io.github.small-scope-qt/patches/0001-install.patch

GUI for small-scope arduino oscilloscope
Log: add software name--small-scope-qt

build: add small-scope-qt

---

io.github.esptool-gui/linglong.yaml
io.github.esptool-gui/patches/0001-install.patch

A GUI for ESP8266 flash tool esptool-ck with basic features, geared towards being a production flashing tool.
Log: add software name--esptool-gui

build: add esptool-gui

---

io.github.djvu-imager-qt/linglong.yaml
io.github.djvu-imager-qt/patches/0001-install.patch

It is based on the combination of the background glueing and mask coloring methods.
Log: add software name--djvu-imager-qt

build: add djvu-imager-qt

---

io.github.MultiupMaNaGeR/linglong.yaml
io.github.MultiupMaNaGeR/patches/0001-install.patch

Multiup MaNaGeR is a software written in Qt/C++ that can send files to the multiupload website : multiup.org.
Log: add software name--MultiupMaNaGeR

build: add MultiupMaNaGeR

---

io.github.Graphical-Serial-Terminal/linglong.yaml
io.github.Graphical-Serial-Terminal/patches/0001-install.patch

A graphical serial terminal
Log: add software name--Graphical-Serial-Terminal

build: add Graphical-Serial-Terminal

---

io.github.qt5ct/linglong.yaml

Qt5 Configuration Tool
Log: add software name--qt5ct

build: add qt5ct

---

io.github.mdiedit/linglong.yaml

Simple text editor with MDI interface
Log: add software name--mdiedit

build: add mdiedit

---

io.github.quickterminal/linglong.yaml
io.github.quickterminal/patches/0001-install.patch

Lightweight terminal emulator
Log: add software name--quickterminal

build: add quickterminal

---

io.github.QComicBook/linglong.yaml

Viewer for comic book archives that aims at convenience and simplicity
Log: add software name--QComicBook

build: add QComicBook

---

io.github.openfool/linglong.yaml
io.github.openfool/patches/0001-install.patch

Open source implementation of a Fool (Durak) card game
Log: add software name--openfool

build: add openfool

---

io.github.posterazor/linglong.yaml
io.github.posterazor/patches/0001-install.patch

The PosteRazor cuts a raster image into pieces which can afterwards be printed out and assembled to a poster.
Log: add software name--posterazor

build: add posterazor

---

io.github.pumpa/linglong.yaml
io.github.pumpa/patches/0001-install.patch

Pumpa is a simple [pump.io][1] client written in C++ and Qt
Log: add software name--pumpa

build: add pumpa

---

io.github.fritzing-app/linglong.yaml

The Fritzing application is an Electronic Design Automation software with a low entry barrier, suited for the needs of makers and hobbyists.
Log: add software name--fritzing-app

build: add fritzing-app

---

io.github.cen64-qt/linglong.yaml
io.github.cen64-qt/patches/0001-install.patch

A customizable frontend for CEN64
Log: add software name--cen64-qt

build: add cen64-qt

---

io.github.kronos/linglong.yaml
io.github.kronos/patches/0001-install.patch

Kronos is a desktop application for logging time in Jira
Log: add software name--kronos

build: add kronos

---

io.github.QtScrobbler/linglong.yaml
io.github.QtScrobbler/patches/0001-install.patch

QTScrobbler ships both multiplatform GUI and CLI versions
Log: add software name--QtScrobbler

build: add QtScrobbler

---

io.github.StudyFolderOrganizer-GUI/linglong.yaml
io.github.StudyFolderOrganizer-GUI/patches/0001-install.patch

Mange your study folders in a easy and time saving way. A easy to use graphical app. GUI Version of the StudyFolderOrganizer console app
Log: add software name--StudyFolderOrganizer-GUI

build: add StudyFolderOrganizer-GUI

---

io.github.bpmdetect/linglong.yaml
io.github.bpmdetect/patches/0001-install.patch

BPMDetect is automatic BPM (beats per minute) detection utility.
Log: add software name--bpmdetect

build: add bpmdetect

---

io.github.terminal-finances/linglong.yaml
io.github.terminal-finances/patches/0001-install.patch

Personal Financial Management
Log: add software name--terminal-finances

build: add terminal-finances

---

io.github.exo/linglong.yaml

Qt GUI, MPRIS interface and a scrobbler for MOC console player / Cmus
Log: add software name--exo

build: add exo

---

io.github.QtFlappyBird/linglong.yaml
io.github.QtFlappyBird/patches/0001-fix.patch

Qt编写的 FlappyBird
log: add game

build: add app QtFlappyBird

---

io.github.PMP/linglong.yaml
io.github.PMP/patches/0001-fix.patch

A multi-user client-server music player with advanced file tracking
log: add app

build: add app PMP

---

io.github.SubAlign/linglong.yaml
io.github.SubAlign/patches/0001-fix-header.patch
io.github.SubAlign/patches/0001-fix.patch

Implementation of the original Merlijn van Veen calculator for aligning mains with subs.
log: add app

build: add app SubAlign

---

io.github.LightCombatManager/linglong.yaml
io.github.LightCombatManager/patches/0001-fix.patch

A small, lightweight cross-platform combat manager for d20-based role-playing games, based on Qt.
log: add app

build: add app LightCombatManager

---

io.github.qputty/linglong.yaml
io.github.qputty/patches/fix-icon.patch
io.github.qputty/patches/fix-install.patch
io.github.qputty/patches/fix-putty.patch

A qt 5 port for putty, the free telnet/ssh client
Log: add app qputty-qt5

build: add app qputty-qt5

---

io.github.qcheckers/linglong.yaml
io.github.qcheckers/patches/fix-icon.patch
io.github.qcheckers/patches/fix-install.patch

QCheckers is a Qt-based checkers board game.
Log: add app QCheckers

build: add app qcheckers

---

io.github.qcad/linglong.yaml
io.github.qcad/patches/fix-3rdparty.patch
io.github.qcad/patches/fix-desktop.patch
io.github.qcad/patches/fix-install.patch

QCAD Community Edition 是一个计算机辅助设计应用 (CAD)。
Log: add app qcad

build: add app qcad
