linuxdeepin/linglong-hub

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yaml
add issue_template
Log: add issue_template
> feat: add issue_template

- org.deepin.demo/linglong.yaml
> test: add test demo

- eu.ototu.Quteqoins/linglong.yaml
详细描述：移植、编译Quteqoins进玲珑，app链接：https://flathub.org/apps/eu.ototu.Quteqoin
Log: 编译完成
> 类型: add Quteqoins

- com.interversehq.qView/linglong.yaml
upload a tool to preview picture.
> build: add qView

- com.gitlab.cutecom.cutecom/linglong.yaml
upload a graphical serial terminal
> build: add Cutecom

- io.github.RedPanda/linglong.yaml
> Add software RedPanda

- automake/linglong.yaml
Tool for generating GNU Standards-compliant Makefiles.
Log: add lib name--automake
> add automake

- io.github.LibreMines/linglong.yaml
Finish build LibreMines for ll-build
Log: 完成LibreMines的编译
> build: add LibreMines

- io.github.yuview/linglong.yaml
Finish build yuview for ll-build
Log: 完成yuview的编译
> build: add yuview

- io.github.textosaurus/linglong.yaml
Finish build textosaurus for ll-build
Log: 完成textosaurus的编译
> build: add textosaurus

- net.blumia.pineapple-pictures/linglong.yaml
详细描述：移植、编译pineapple-pictures进玲珑，项目地址：https://github.com/BLumia/pineapple-pictures
Log: 编译完成
> pineapple-pictures is a photoviewer.

- io.github.ksnip.kColorPicker/linglong.yaml
upload a lib for kImageAnnotator
> build: add kColorPicker

- kIamgeAnnotator/linglong.yaml
> build: add kImageAnnotator

- io.github.ksnip/linglong.yaml
Ksnip is a Qt-based cross-platform screenshot tool that provides many annotation features for your screenshots.
> build: add ksnip

- libsdl3/linglong.yaml
libsdl2 already exists in the library, add libsdl3 here
> build: add libsdl3

- help2man/linglong.yaml
build the help2man lib for linglong
log: 编译help2man库进玲珑
> build: add_help2man_lib

- io.github.qgit/linglong.yaml
With qgit you will be able to browse revisions history, view patch content and changed files, graphically following different development branches.
Log: add software name--qgit
> build: add qgit

- libtool/linglong.yaml
编译成功
Generic library support script.
Log: add  lib--libtool
> build: add libtool

- leptonica/linglong.yaml
编译成功
Leptonica is an open source library containing software that is broadly useful for image processing and image analysis applications.
log: add lib--leptonica
> build: add leptonica

- io.github.Groot/linglong.yaml
Groot is a Graphical Editor, to create BehaviorTrees.
Log: add software name--Groot
> build: add Groot

- .reuse/dep5
> chore: set license for patches

- libndp/linglong.yaml
finish build libndplib for ll-builder.
log: 完成libndp的编译。
> build: add libndp

- automake1.11/linglong.yaml
add "mkdir /runtime/share/aclocal && ln -s /runtime/share/aclocal-1.11  /runtime/share/aclocal"
log: edit details
> update: automake1.11

- io.github.oneko/linglong.yaml
- io.github.oneko/patches/0001-install.patch
编译了一只跟随鼠标的小猫
Log: add software name--oneko
> build: add oneko

- io.github.randombit.botan/linglong.yaml
build lib:botan
Finish build lib:botan for ll-builder
Log:完成对botan的编译
> build lib:botan

- io.github.pipewalker/linglong.yaml
> build: add pipewalker

- LuaJIT/linglong.yaml
详细描述：编译lua语言库，项目地址：https://github.com/LuaJIT/LuaJIT
Log: 编译完成
> build: add LuaJIT

- ccrypt/linglong.yaml
编译成功
Encryption and decryption.
Log: add lib name--ccrypt
> build: add ccrypt

- io.github.flycast/linglong.yaml
> bulid: add app flycast

- io.github.Symphonium/linglong.yaml
A tool to help when learning to play the piano.
Log: add software name--Symphonium
> build: add Syphonium

- opencv/linglong.yaml
opencv3.2,opencv2.4.9 already exeist,add opencv4.x
> build: add opencv(4.X)

- io.github.PuNES/linglong.yaml
Finfish build PuNES for ll-build
Log: 完成PuNES的编译
> build: add PuNES

- io.github.pacmanlogviewer/linglong.yaml
> build: add app pacmanlogviewer

- com.gitlab.sayonara-player/linglong.yaml
Finish build sayonara-player for ll-build
Log: 完成sayonara-player的编译
> build: add sayonara-player

- io.github.focuswriter/linglong.yaml
> build: add app focuswriter

- curl/linglong.yaml
Curl is a command-line tool for transferring data specified with URL syntax.
> build: add curl

- io.github.WizQTClient/linglong.yaml
WizNote is an open-sourced project, published under GPLv3 for individual/personal users and custom commercial license for company users.
> build: add WizQTClient

- io.github.media-downloader/linglong.yaml
This project is a Qt/C++ based GUI frontend to CLI multiple CLI based tools that deal with downloading online media.
> build: add media-downloader

- io.github.powerkit/linglong.yaml
> build: add app powerkit

- io.github.QMPlay2/linglong.yaml
> build: add app QMPlay2

- io.github.moviesquare/linglong.yaml
Qt based stylish feature-rich Linux Desktop client for TMDb (http://www.themoviedb.org), the free and community maintained movie database with over millions of movies.
> build: add moviesquare

- io.github.qlipper/linglong.yaml
> build: add app qlipper

- yaml-cpp/linglong.yaml
Finish build lib yaml-cpp for ll-build
Log: 完成lib：yaml-cpp的编译
> build: add yaml-cpp

- toxcore/linglong.yaml
> build: add toxcore

- capstone/linglong.yaml
build: lib for capstone
description: capstone是反编译框架，在之后的很多反编译软件中都会使用到它
Log:build lib capstone is success
> build: lib for capstone

- qtilitools/linglong.yaml
为应用qruler添加依赖包。
Log: finish lib qtilitools。
> build: add lib qtilitools

- hunspell/linglong.yaml
> build: add lib hunspell

- io.github.qliquidsfz/linglong.yaml
> build: add app qliquidsfz

- io.github.qvge/linglong.yaml
QVGE is a multiplatform graph editor written in C++/Qt. Its main goal is to make possible visually edit two-dimensional graphs in a simple and intuitive way.
> build: add qvge

- io.github.qtictactoe/linglong.yaml
qtictactoe是一款简单的支持2人对战的连连看小游戏。
Log: finish app qtictactoe.
> build: add qtictactoe

- io.github.MazeSolver/linglong.yaml
Create and solve mazes using DFS or BFS algorithm.
Log: add software name--MazeSolver
> build: add MazeSolver

- io.github.Ascii-Design/linglong.yaml
> build: add app Ascii-Design

- io.github.RandomWordlistGenerator/linglong.yaml
> build: add app RandomWordlistGenerator

- io.github.KDiskMark/linglong.yaml
> build: add app KDiskMark

- flatbuffers/linglong.yaml
> build: add lib flatbuffers

- io.github.q4wine/linglong.yaml
Q4Wine is a Qt GUI for W.I.N.E. It will help you manage wine prefixes and installed applications.
> build: q4wine

- pcre2/linglong.yaml
build lib:PCRE2
Finish PCRE2 build lib:PCRE2 for ll-builder
> build : add lib PCRE2

- io.github.SimpleNormalMapper/linglong.yaml
> build: add app SimpleNormalMapper

- io.github.QtMips/linglong.yaml
> build: add app QtMips

- io.github.A-Photo-Tool-Libre/linglong.yaml
- io.github.A-Photo-Tool-Libre/patches/src.patch
Easy to use photo editing software.
Logs:add app name--A-Photo-Tool-Libre
> build: add app A-Photo-Tool-Libre

- io.github.qFlipper/linglong.yaml
> build: add app qFlipper

- io.github.qruler/linglong.yaml
一个小尺子工具，测量距离。
Log: finish app qruler.
> build: add qruler

- io.github.qspeakers/linglong.yaml
> build: add app qspeakers

- io.github.magnifiqus/linglong.yaml
一个小工具，完成放大镜操作。
Log: finish app magnifiqus.
> build: add magnifiqus

- ksyndication/linglong.yaml
An RSS/Atom parser library
log: add lib-ksyndication
> build: add lib ksyndication

- io.github.LIII/linglong.yaml
multi-platform bittorrent client.
log: add software--Liii
> build: add Liii

- io.github.FeatherNote/linglong.yaml
a lightweight Qt hierarchical notes-manager for Linux.
Log: add software name--FeatherNote
> build: add FeatherNote

- io.github.MarkdownEdit/linglong.yaml
Experience the speed and simplicity of MarkdownEdit
Log: add software name--MarkdownEdit
> build: add MarkdownEdit

- io.github.JQTools/linglong.yaml
- io.github.JQTools/patches/install.patch
Jason Qt Tools.
Logs: 一个基于qt的工具包
> build: add app JQTools

- io.github.qmlevemon/linglong.yaml
- io.github.qmlevemon/patches/0001-fix-install.patch
Qt5/QML based EVE Online character monitor
log: add software--qmlevemon
> build: add qmlevemon

- io.github.Advanced_Chess/linglong.yaml
- io.github.Advanced_Chess/patches/0001-fix-install.patch
Graphical 2P chess built with Qt Quick QML and C++.
log: add game Advanced_Chess
> build: add Advanced_Chess

- io.github.SuperMario/linglong.yaml
- io.github.SuperMario/patches/0001-fix-install.patch
a simple mario game.
log: add game--Super_Mario
> build: add Super_Mario

- io.github.coinflip-gtk/linglong.yaml
- io.github.coinflip-gtk/patches/fix_coinflip.patch
> build: add app coinflip-gtk

- io.github.BesLyric-for-X/linglong.yaml
- io.github.BesLyric-for-X/patches/install.patch
BesLyric-for-X is a song lyrics production software.
Logs: 编译了一个网易云主题风格的歌词制作app
> build: add app Beslyric-for-X

- io.github.vimix/linglong.yaml
- io.github.vimix/patches/fix_vimix.patch
> build: add app vimix

- io.github.canorus/linglong.yaml
- io.github.canorus/patches/0001-fix-install.patch
Canorus - a free music score editor
log: add software canorus
> build: add canorus

- io.github.strawberry/linglong.yaml
Strawberry is a music player and music collection organizer.
Log: add software name--strawberry
> build: add strawberry

- io.github.photoquick/linglong.yaml
- io.github.photoquick/patches/0001-fix-install.patch
A simple handy image viewer and editor with some useful features (Qt based).
log: add software--photoqucik
> build: add photoquick

- io.github.HolySheet/linglong.yaml
- io.github.HolySheet/patches/0001-fix-install.patch
A cross platform application for managing datasheet - Written in Qt5 / C++.
log: add software--HolySheet
> build: add HolySheet

- io.github.orbvis/linglong.yaml
- io.github.orbvis/patches/fix_orbvis.patch
> build: add app orbvis

- io.github.QJsonify/linglong.yaml
- io.github.QJsonify/patches/0001-fix-install.patch
Prettify and Minify your JSON files locally. Don't give out your precious information to online sources.
log: add software--QJsonify
> build: add QJsonify

- io.github.QWeave/linglong.yaml
Visualization of weaving patterns
Log: add software name--QWeave
> build: add QWeave

- io.github.qvkbd/linglong.yaml
> build: add qvkbd

- io.github.midieditor/linglong.yaml
- io.github.midieditor/patches/fix_midieditor.patch
> build: add app midieditor

- io.github.notepanda/linglong.yaml
Finish build notepanda for ll-build
Log: 完成notepanda的编译
> build: add notepanda

- io.github.FeatherNotes/linglong.yaml
FeatherNotes (by Pedram Pourang, a.k.a. Tsu Jan tsujan2000@gmail.com) is a lightweight Qt hierarchical notes-manager for Linux.
log: add software--FeatherNotes
> build: add FeatherNotes

- io.github.SmartHacker/linglong.yaml
- io.github.SmartHacker/patches/0001-fix-install.patch
Tool to automatically decode unknown SmartMeter data formats via "cypher known plaintext 'attack'" / intelligent brute forcing. A QT/GUI driven inspector for working with SmartMeter data. Blazingly fast! Compact C++ routines ready for embedded use!
log: add software--SmartHacker
> build: add SmartHacker

- io.github.jamulus/linglong.yaml
Finish build jamulus for ll-build
Log: 完成jamulus的编译
> build: add jamulus

- io.github.Seamly2D/linglong.yaml
Finish build Seamly2D for ll-build
Log: 完成Seamly2D的编译
> build: add Seamly2D

- io.github.esee/linglong.yaml
esee provides a UI for editing the EXIF data in JPG files.
Log: add software name--esee
> build: add esee

- io.github.cpeditor/linglong.yaml
CP Editor - Boost your competitive programming experience!
Log: add software name--cpeditor
> build: add cpeditor

- io.github.IanniX/linglong.yaml
IanniX is a graphical open-source sequencer, based on Iannis Xenakis works, for digital art
Log: add software name--IanniX
> build: add IanniX

- io.github.QtWuziqi/linglong.yaml
- io.github.QtWuziqi/patches/0001-fix-install.patch
a simple wuziqi game
log: add software--QtWuziqi
> build: add QtWuziqi

- io.github.flow-pomodoro/linglong.yaml
- io.github.flow-pomodoro/patches/fix-001.patch
一款代办清单小工具，提高工作效率
Log: finish app flow-pomodoro.
> build: add flow-pomodoro

- io.github.qtjsondiff/linglong.yaml
Some kind of diff viewer for Json (based on tree like json container/viewer widget).
Log: add software name--qtjsondiff
> build: add qtjsondiff

- io.github.metronomek/linglong.yaml
Finish build metronomek for ll-build
Log: 完成app：metronomek的编译
> build: add metronomek

- io.github.magicfountain/linglong.yaml
A screenwriting program available
Log: add software name--magicfountain
> build: add magicfountain

- io.github.QtTube/linglong.yaml
- io.github.QtTube/patches/add-desktop-file-patch.patch
- io.github.QtTube/patches/install-desktop-file-patch.patch
A Qt frontend for YouTube.
Log: add software name--QtTube
编译成功
> build: add QtTube

- io.github.panini/linglong.yaml
Panini is a visual tool for creating perspective views from panoramic and wide angle photographs.
Log: add software name--panini
> build: add panini

- io.github.mpz/linglong.yaml
Music player for big local collections
Log: add software name--mpz
> build: add mpz

- io.github.QtPass/linglong.yaml
- io.github.QtPass/patches/0001-fix-install.patch
QtPass is a GUI for pass, the standard unix password manager.
log: add software--QtPass
> build: add QtPass

- io.github.cubiomes-viewer/linglong.yaml
- io.github.cubiomes-viewer/patches/0001-fix-install.patch
Cubiomes Viewer provides a graphical interface for the efficient and flexible seed-finding utilities provided by cubiomes and a map viewer for the Minecraft biomes and structure generation.
log: add sodtware--cubiomes
> build: add cubiomes-viewer

- io.github.Video-Format-Converter/linglong.yaml
- io.github.Video-Format-Converter/patches/0001-fix-install.patch
Video Converter is a simple, cross-platform graphical user interface (GUI) application built with Qt and FFmpeg. It allows users to easily convert video files from one format to another, making it a handy tool for video enthusiasts and professionals.
log: add software--Video-Format-Converter
> build: add Video-Format-Converter

- io.github.sudoku/linglong.yaml
- io.github.sudoku/patches/0001-fix-install.patch
This is a simple Sudoku Puzzle game made with C++ and Qt5.
log: add game--sudoku
> build: add sudoku

- io.github.llk/linglong.yaml
- io.github.llk/patches/0001-fix-desktop.patch
A game where you connect stuff together.
log: add game-llk
> build: add llk

- aspell/linglong.yaml
this is the Git repository for GNU Aspell.
log: add software--aspell
> build: add lib aspell

- kcompletion/linglong.yaml
Log: add lib name--kcompletion
> build: add kcompletion

- immer/linglong.yaml
> build: add lib immer

- zug/linglong.yaml
> build: add lib zug

- cn.wps.wps-office/linglong.yaml
WPS Office, is an office productivity suite.
WPS Office including Writer, Presentation
and Spreadsheets, is a powerful office suite, which is able to process word file, produce wonderful slides, and analyze data as well. It is deeply compatible with all of the latest Microsoft Office file formats. It can easily open and read the documents created with Microsoft Office. This is the Linux version, and it's now a TESTING package. Welcome to our website: http://wps-community.org
log: add wps
> build: add wps

- lager/linglong.yaml
- lager/patches/0001-install.patch
> build: add lager

- libexiv2/linglong.yaml
> build: add lib exiv2

- Catch2/linglong.yaml
> build: add lib Catch2

- cn.wps.wps-office/linglong.yaml
Log: change wps_binary commit id , update the icon path ,fix desktop not available
> build: update wps

- kitemmodels/linglong.yaml
Log: add lib name--kitemmodels
> build: add lib kitemmodels

- kitemviews/linglong.yaml
> build: add lib kitemviews

- kwidgetsaddons/linglong.yaml
Log: add lib name--kwidgetsaddons
> build: add kwidgetsaddons

- kguiaddons/linglong.yaml
> build: add kguiaddons

- xorg-macros/linglong.yaml
Log: add lib name--xorg-macros
> build: add lib xorg-macros

- automake1.14.0/linglong.yaml
Log: add lib  name--automake1.14.0
> build: add lib automake1.14.0

- io.github.MemoryCards/linglong.yaml
- io.github.MemoryCards/patches/install.patch
Finish build MemoryCards for ll-build
Log: 完成MemoryCards的编译
> build: add MemoryCards

- io.github.yoDownet/linglong.yaml
Finish build yoDownet for ll-build
Log: 完成yoDownet的编译
> build: add yoDownet

- io.github.smilla-enlarger/linglong.yaml
- io.github.smilla-enlarger/patches/add-desktop-file-patch.patch
- io.github.smilla-enlarger/patches/install-desktop-file-patch.patch
Finish build app:smilla-enlarger for ll-build
Log: 完成对App：smilla-enlarger的编译
> build: add smilla-enlarger

- io.github.mousePointerHelper/linglong.yaml
- io.github.mousePointerHelper/patches/fix-001.patch
帮助用户调整光标位置的迷你应用程序.
Log: finish app mousePointerHelper.
> build: add mousePointerHelper

- io.github.NormalmapGenerator/linglong.yaml
- io.github.NormalmapGenerator/patches/add-desktop-file-patch.patch
- io.github.NormalmapGenerator/patches/install-desktop-file-patch.patch
Log: 完成App：NormalmapGenerator的编译
> build: add NormalmapGenerator

- io.github.Calculator/linglong.yaml
- io.github.Calculator/patches/fix_calc.patch
> build: add app Calculator

- io.github.CandyCrush/linglong.yaml
- io.github.CandyCrush/patches/0001-install.patch
Finish build CandyCrush for ll-build
Log: 完成App: CandyCrush的编译
> build: add CandyCrush

- io.github.DrawingApp/linglong.yaml
- io.github.DrawingApp/patches/0001-install.patch
A simple drawing app.
Logs: add app name--DrawingApp
> build: add app DrawingApp

- io.github.Groot/io.github.QalculaTor/linglong.yaml
- io.github.Groot/io.github.QalculaTor/patches/fix-desktop.patch
更加自定义化的计算器，一款简单的计算器小工具。
Log: finish app QalculaTor.
> build: QalculaTor

- io.github.isometric_tiles_qt/linglong.yaml
- io.github.isometric_tiles_qt/patches/0001-install.patch
Finish build isometric_tiles_qt for ll-build
Log: 完成App: isometric_tiles_qt的编译
> build: add isometric_tiles_qt

- io.github.MemoryPuzzle_Qt-Cpp/linglong.yaml
- io.github.MemoryPuzzle_Qt-Cpp/patches/0001-install.patch
Finish build MemoryPuzzle_Qt-Cpp  for ll-build
Log: 完成App: MemoryPuzzle_Qt-Cpp的编译
> build: add MemoryPuzzle_Qt-Cpp

- io.github.SimonGame_Qt-Cpp/linglong.yaml
- io.github.SimonGame_Qt-Cpp/patches/0001-install.patch
Finish build SimonGame_Qt-Cpp for ll-build
Log: 完成App: SimonGame_Qt-Cpp的编译
> build: add SimonGame_Qt-Cpp

- io.github.QtChess/linglong.yaml
- io.github.QtChess/patches/add-desktop-file-patch.patch
- io.github.QtChess/patches/install-desktop-file-patch.patch
Finish build QtChess for ll-build
Log: 完成对App：QtChess的编译
> build: add QtChess

- io.github.Log2Log/linglong.yaml
- io.github.Log2Log/patches/add-desktop-file-patch.patch
- io.github.Log2Log/patches/install-desktop-file-patch.patch
Finish build app: Log2Log for ll-build
Log: 完成App：Log2Log的编译
> build: add Log2Log

- io.github.techvscats/linglong.yaml
- io.github.techvscats/patches/0001-install.patch
塔防游戏.
Logs: add app name--techvscats
> build: add app techvscats

- io.github.qt2048/linglong.yaml
- io.github.qt2048/patches/0001-install.patch
qt2048.
Logs: add app name--qt2048
> build: add app qt2048

- io.github.SkyWar-MiniGame/linglong.yaml
- io.github.SkyWar-MiniGame/patches/0001-install.patch
SkyWar.
Logs: add app name--SkyWar-MiniGame
> build: add app SkyWar-MiniGame

- io.github.litetran/linglong.yaml
> build: add app litetran

- io.github.Jerry-Rig/linglong.yaml
- io.github.Jerry-Rig/patches/0001-install.patch
A GUI wrapper for both FFMPEG and LibAv to help my friend Jerry compress videos. Its basically like handbrake, except the output isn't garbage.
Logs: add app name--Jerry-Rig
> build: add app Jerry-Rig

- io.github.QReversi/linglong.yaml
- io.github.QReversi/patches/0001-fix-install.patch
A Qt-based reversi game.
log: add game--QReversi
> build: add QReversi

- io.github.NotePadApplication/linglong.yaml
- io.github.NotePadApplication/patches/add-desktop-file-patch.patch
- io.github.NotePadApplication/patches/install-desktop-file-patch.patch
Finish build NotePadApplication for ll-build
Log: 完成App: NotePadApplication的编译
> build: add NotePadApplication

- io.github.LinEditor/linglong.yaml
- io.github.LinEditor/patches/add-desktop-file-patch.patch
- io.github.LinEditor/patches/install-desktop-file-patch.patch
Finish build LinEditor for ll-build
Log: 完成App: LinEditor的编译
> build: add LinEditor

- hyphen/linglong.yaml
Hyphen - hyphenation library to use converted TeX hyphenation patterns
a lib for qtwebkit
> build: add lib hyphen

- io.github.QtKeyboard/linglong.yaml
- io.github.QtKeyboard/patches/0001-fix-install.patch
a simple QtKeyboard.
log: add software--QtKeyboard
> build: add QtKeyboard

- io.github.Music-Player/linglong.yaml
- io.github.Music-Player/patches/0001-install.patch
Music-Player
Logs: add app name--Music-Player
> build: add app Music-Player

- io.github.Black-and-White-QT/linglong.yaml
- io.github.Black-and-White-QT/patches/0001-install.patch
Finish build Black-and-White-QT  for ll-build
Log: 完成App:Black-and-White-QT的编译
> build: add Black-and-White-QT

- io.github.ytbtocue/linglong.yaml
- io.github.ytbtocue/patches/0001-install.patch
This program is intended to download audio albums from YouTube.
Log: add software name--ytbtocue
> build: add ytbtocue

- io.github.Clevit/linglong.yaml
> build: add Clevit

- io.github.Qt_FreeCell/linglong.yaml
- io.github.Qt_FreeCell/patches/0001-fix-install.patch
game FreeCell.
log: add game--FreeCell
> build: add Qt_FreeCell

- io.github.GreedySnake/linglong.yaml
- io.github.GreedySnake/patches/0001-fix-install.patch
a simple GreedySnake game.
log: add game--GreedySnake
> build: add GreedySnake

- io.github.Notepad-DOT-Qt/linglong.yaml
- io.github.Notepad-DOT-Qt/patches/0001-fix-install.patch
Notepad DOT Qt is an open source, cross-platform and highly customizable text editor. It has all the essential notepad features with more handy stuff. It is suitable for everyday use, from beginners to advanced users.
log: add software--Notepad-DOT-Qt
> build: add Notepad-DOT-Qt

- io.github.FiveGame/linglong.yaml
- io.github.FiveGame/patches/0001-install.patch
局域网五子棋对战
Log: add software name--FiveGame
> build: add FiveGame

- io.github.ImageEditor/linglong.yaml
- io.github.ImageEditor/patches/0001-install.patch
图片编辑浏览器
Log: add software name--ImageEditor
> build: add ImageEditor

- io.github.Draughts/linglong.yaml
- io.github.Draughts/patches/0001-install.patch
Online Draughts game implemented with Qt 5.
Logs: add app name--Draughts
> build: add app Draughts

- io.github.SoundGenerator/linglong.yaml
- io.github.SoundGenerator/patches/0001-install.patch
Sound Generator with nodal interface in Qt to create sounds from scratch.
Log: add software name--SoundGenerator
> build: add SoundGenerator

- io.github.DotaCardDuel2/linglong.yaml
- io.github.DotaCardDuel2/patches/0001-install.patch
DotaCard.
Logs: add app name--DotaCardDuel2
> build: add app DotaCardDuel2

- io.github.IconEditor/linglong.yaml
- io.github.IconEditor/patches/0001-install.patch
图标颜色编辑器
Log: add software name--IconEditor
> build: add IconEditor

- io.github.Calculate/linglong.yaml
- io.github.Calculate/patches/0001-install.patch
查找通过不同运算得到相同结果的数的组合！
Log: add software name--Calculate
> build: add Calculate

- io.github.tcpview/linglong.yaml
- io.github.tcpview/patches/0001-install.patch
Graphical network connections viewer for Linux
Log: add software name--tcpview
> build: add tcpview

- io.github.qt-todo/linglong.yaml
- io.github.qt-todo/patches/add-desktop-file-patch.patch
- io.github.qt-todo/patches/install-desktop-file-patch.patch
Finish build qt-todo for ll-build
Log: 完成qt-todo的编译
> build: add qt-todo

- io.github.QtLianliankan/linglong.yaml
- io.github.QtLianliankan/patches/fix-001.patch
一个游戏：连连看。
Log: finish app QtLianliankan.
> build: add app QtLianliankan

- io.github.ssr/linglong.yaml
- io.github.ssr/patches/0001-install.patch
SimpleScreenRecorder is a screen recorder for Linux.
Logs: add app name--ssr
> build: add app ssr

- io.github.Scheduler/linglong.yaml
- io.github.Scheduler/patches/0001-install.patch
Scheduler.
Logs: add app name--Scheduler
> build: add app Scheduler

- io.github.YAWYSIWYGEE/linglong.yaml
- io.github.YAWYSIWYGEE/patches/add-desktop-file-patch.patch
- io.github.YAWYSIWYGEE/patches/install-desktop-file-patch.patch
Finish build YAWYSIWYGEE for ll-build
Log: 完成app：YAWYSIWYGEE的编译
> build: add YAWYSIWYGEE

- io.github.bew/linglong.yaml
- io.github.bew/patches/fix-001.patch
BEW可帮助您使用图形用户界面将Web应用程序转换为桌面Web应用程序（BEW）。
Log: finish app bew.
> build: add app bew

- io.github.QMines/linglong.yaml
- io.github.QMines/patches/install.patch
Finish build QMines for ll-build
Log: 完成QMines的编译
> build: add QMines

- io.github.SkyMPC/linglong.yaml
- io.github.SkyMPC/patches/0001-install.patch
a simple MPD (Music Player Daemon) client, powerd by Qt
Log: add software name--SkyMPC
> build: add SkyMPC

- io.github.QArkanoid/linglong.yaml
- io.github.QArkanoid/patches/0001-fix-install.patch
Simple "Arkanoid" type game, based on QT libraries, with sounds.
log: add software--QArkandoid
> build: add QArkanoid

- io.github.hexglass/linglong.yaml
- io.github.hexglass/patches/0001-fix-install.patch
the HexGlass is a Tetris-like puzzle game
log: add game-hexlass
> build: add hexlass

- io.github.memory-game/linglong.yaml
- io.github.memory-game/patches/0001-fix-install.patch
Memory game coded using Qt framework.
log: add game--memory
> build: add memory-game

- io.gitlab.crqt-ng/linglong.yaml
build: app for reading
Logs:build app for reading is success!
> build: app for reading

- io.github.2048/linglong.yaml
- io.github.2048/patches/fix-001.patch
一款2048小游戏。
Log: finish app 2048.
> build: add 2048

- io.github.fairseabattle/linglong.yaml
- io.github.fairseabattle/patches/0001-fix-install.patch
The FairSeaBattle -- sink the computer's fleet.
log: add game--fairseabattle
> build: add fairseabattle

- io.github.Furtherance-qt/linglong.yaml
- io.github.Furtherance-qt/patches/fix_furth.patch
> build: add app Furtherance-qt

- io.github.Sudoku_game_2021/linglong.yaml
- io.github.Sudoku_game_2021/patches/0001-fix-install.patch
Game that shall be Written using C++ standards 14/17
log: add game--Sudoku_game_2021
> build: add Sudoku_game_2021

- io.github.kroketgraph/linglong.yaml
- io.github.kroketgraph/patches/0001-fix-install.patch
graphical graph visualization viewer with qt gui and subgraph folding feature.
log: add software--kroketgraph
> build: add kroketgraph

- io.github.IslandRacer/linglong.yaml
- io.github.IslandRacer/patches/0001-fix-install.patch
A small qt-based Racegame.
log: add game--IslandRacer
> build: add IslandRacer

- io.github.simple-image-filter/linglong.yaml
imple-image-filter is a QT software that can handle image rotation, clipping, basic beauty, filter and other functions ImageProcess，using Qt,filter
Log: add software name--simple-image-filter
> build: add simple-image-filter

- io.github.perfecttin/linglong.yaml
Finish build perfecttin for ll-build
Log: 完成perfecttin的编译
> build: add perfecttin

- io.github.treesheets/linglong.yaml
TreeSheets：自由格式数据组织器（请参阅 strlen.com/treesheets）
Log: finish app treesheets.
> build: add treesheets

- io.github.gencolormap/linglong.yaml
- io.github.gencolormap/patches/fix_gcm.patch
> build: add app gencolormap-gui

- io.github.Three-men-s-morris-game/linglong.yaml
- io.github.Three-men-s-morris-game/patches/0001-install.patch
Three men's morris game created in Qt creator framework. Simple 2d game. Also include all resources files.
Logs: add app name--Three-men-s-morris-game
> build: add app Three-men-s-morris-game

- io.github.Analysis/linglong.yaml
- io.github.Analysis/patches/fix_install.patch
Potentiostat GUI in Qt for biological analysis.
Logs: add app name--Analysis
> build: add app Analysis

- io.github.EliminateGame/linglong.yaml
- io.github.EliminateGame/patches/0001-install.patch
A eliminate game made by Qt Creator. Based on other's open source code.
Logs: add app name--EliminateGame
> build: add app EliminateGame

- io.github.SmartCode/linglong.yaml
- io.github.SmartCode/patches/0001-install.patch
Official IDE for LegoLang
Log: add software name--SmartCode
> build: add SmartCode

- io.github.DustRacing2D/linglong.yaml
- io.github.DustRacing2D/patches/fix-001.patch
> build: add app dustrac-editor

- io.github.Tetris/linglong.yaml
- io.github.Tetris/patches/fix-001.patch
一款小游戏：俄罗斯方块。
Log: finish app Tetris.
> build: add app Tetris

- io.github.olam/linglong.yaml
- io.github.olam/patches/install.patch
Finish build olam for ll-build
Log: 完成对App：olam的编译
> build: add olam

- io.github.lin_guider/linglong.yaml
- io.github.lin_guider/patches/add-desktop-file-patch.patch
- io.github.lin_guider/patches/install-desktop-file-patch.patch
Finish build app: lin_guider for ll-build
Log: 完成对App：lin_guider的编译
> build: add lin_guider

- io.github.snake-game/linglong.yaml
- io.github.snake-game/patches/0001-install.patch
A snake game based on Qt.
Log: add software name--snake-game
> build: add snake-game

- io.github.Dwarf-Therapist/linglong.yaml
- io.github.Dwarf-Therapist/patches/0001-install.patch
> add Dwarf therapist

- io.github.audio-player/linglong.yaml
- io.github.audio-player/patches/fix_ap.patch
> build: add app audio-player

- io.github.Qt_Gif_Creator/linglong.yaml
- io.github.Qt_Gif_Creator/patches/0001-install.patch
基于Qt的屏幕gif录制工具
Log: add software name--Qt_Gif_Creator
> build: add Qt_Gif_Creator

- io.github.OpenQtPlayer/linglong.yaml
- io.github.OpenQtPlayer/patches/0001-install.patch
openqtmovie 利用QMediaPlay(multimedia) qt的技术实现的一个简单的播放器
Log: add software name--OpenQtPlayer1
> build: add OpenQtPlayer

- io.github.stopwatch/linglong.yaml
- io.github.stopwatch/patches/0001-install.patch
一个简单易用的秒表
Log: add software name--stopwatch
> build: add stopwatch

- io.github.KDCEditor/linglong.yaml
- io.github.KDCEditor/patches/install.patch
Here it is, warts and all. After many more months of hard work and laziness than there ever should have been, it's done. For now, anyway.
log: add app--KDCEditor
> build: add KDCEditor

- io.github.whid/linglong.yaml
- io.github.whid/patches/0001-fix-install.patch
What Have I Done - Time Tracker for Freelancers and Individual Contractors.
log: add software--whid
> build: add whid

- io.github.QtToDoList/linglong.yaml
- io.github.QtToDoList/patches/fix_tl.patch
> build: add app QtToDoList

- io.github.MineSweep/linglong.yaml
- io.github.MineSweep/patches/0001-install.patch
Qt扫雷游戏
Log: add software name--MineSweep
> build: add MineSweep

- io.github.tetris-qt/linglong.yaml
- io.github.tetris-qt/patches/0001-fix-install.patch
a simple game.
log: add game-tetris
> build: add tetris

- io.github.HashiGame/linglong.yaml
- io.github.HashiGame/patches/fix_ho.patch
> build: add app HashiGame

- io.github.ProceduralTextureMaker/linglong.yaml
- io.github.ProceduralTextureMaker/patches/install.patch
Finish build ProceduralTextureMaker for ll-build
Log: 完成ProceduralTextureMaker的编译
> build: add ProceduralTextureMaker

- io.github.compass/linglong.yaml
- io.github.compass/patches/fix_desktop.patch
- io.github.compass/patches/fix_exec.patch
> build: add app compass

- io.github.Draw-Tool/linglong.yaml
- io.github.Draw-Tool/patches/0001-install.patch
绘图工具/图片编辑
Log: add software name--Draw-Tool
> build: add Draw-Tool

- io.github.mmind-qt/linglong.yaml
- io.github.mmind-qt/patches/0001-install.patch
Guess number game.
Logs: add app name--mmind-qt
> build: add app mmind-qt

- io.github.vaktisalah/linglong.yaml
- io.github.vaktisalah/patches/fix_vak.patch
> build: add app vaktisalah

- io.github.MusicBoard/linglong.yaml
- io.github.MusicBoard/patches/0001-install.patch
Welcome to MusicBoard!
Logs:add app name--MusicBoard
> build: add app MusicBoard

- io.github.JDSP4Linux-GUI/linglong.yaml
- io.github.JDSP4Linux-GUI/patches/fix_jdsp.patch
> build: add app JDSP4Linux-GUI

- io.github.baton-editor/linglong.yaml
- io.github.baton-editor/patches/install.patch
Baton is a code editor for C++ Design document:
log: add app--baton-editor
> build: add baton-editor

- io.github.Birthday-App/linglong.yaml
- io.github.Birthday-App/patches/fix_install.patch
This project for a user-friendly desktop application designed to help users keep track of birthdays and never miss an important celebration =).
Logs: add app name--Birthday-App
> build: add app Birthday-App

- io.github.page-hits-tool/linglong.yaml
- io.github.page-hits-tool/patches/0001-install.patch
刷网页点击量工具
Log: add software name--Page-hits-tool
> build: add Page-hits-tool

- io.github.TSWaveMaker/linglong.yaml
- io.github.TSWaveMaker/patches/0001-install.patch
A great trigger, team, script and taskforce editor for C&C Tiberian Sun.
​log: add app--TSWaveMaker
>  build: add TSWaveMaker

- io.github.somafm-qt/linglong.yaml
- io.github.somafm-qt/patches/0001-install.patch
SomaFM Radio (somafm.com) player (desktop, qt5)
Log: add software name--somafm-qt
> build: add somafm-qt

- io.github.laser-engraver/linglong.yaml
- io.github.laser-engraver/patches/0001-install.patch
Simple engraving tool, compose scene with images and labels, create gcode and send it to your engraver.
Log: add software name--laser-engraver
> build: add laser-engraver

- io.github.HTYPinTu/linglong.yaml
- io.github.HTYPinTu/patches/0001-install.patch
Finish build HTYPinTu for ll-build
Log: 完成App: HTYPinTu的编译
> build: add HTYPinTu

- io.github.QtPainter/linglong.yaml
- io.github.QtPainter/patches/fix_qtp.patch
> build: add app QtPainter

- io.github.glabels-qt/linglong.yaml
> build: add app glabels-qt

- libxaw/linglong.yaml
Xaw is the X Athena Widget Set.
log: add lib
> build: add libxaw

- io.github.mirasol/linglong.yaml
- io.github.mirasol/patches/add-desktop-file-patch.patch
- io.github.mirasol/patches/install-desktop-file-patch.patch
Finish build mirasol for ll-build
Log: 完成mirasol的编译
> build: add mirasol

- io.github.QFlappyBird/linglong.yaml
- io.github.QFlappyBird/patches/fix_qfb.patch
> build: add app QFlappyBird

- io.github.ChatAPP/linglong.yaml
- io.github.ChatAPP/patches/fix_cmu.patch
> build: add app ChatAPP

- io.github.QNotePad/linglong.yaml
- io.github.QNotePad/patches/fix_qnotepad.patch
> build: add app QNotePad

- io.github.QImageViewer/linglong.yaml
- io.github.QImageViewer/patches/fix_qiv.patch
> build: add app QImageViewer

- io.github.QT-Alarm-Clock-Application/linglong.yaml
- io.github.QT-Alarm-Clock-Application/patches/fix_msa.patch
新增应用QT-Alarm-Clock-Application
> build: add app QT-Alarm-Clock-Application

- io.github.mltranslator/linglong.yaml
- io.github.mltranslator/patches/add-desktop-file-patch.patch
- io.github.mltranslator/patches/install-desktop-file-patch.patch
Finish build mltranslator for ll-build
Log: 完成对App：mltranslator的编译
> build: add mltranslator

- io.github.QSystemInfo/linglong.yaml
- io.github.QSystemInfo/patches/fix_qsi.patch
> build: addd app QSystemInfo

- io.github.Daedalus/linglong.yaml
- io.github.Daedalus/patches/0001-install.patch
Daedalus is a MineSweeper game.
Logs: add app name--Daedalus
> build: add app Daedalus

- io.github.QT-PigGame/linglong.yaml
- io.github.QT-PigGame/patches/0001-install.patch
Dice game written in Qt using Qt Creator. This is my first Qt MacOS Desktop App, to grasp the basic concepts and get comfortable with the software.
Logs: add app name--QT-PigGame
> build: add app QT-PigGame

- io.github.ContrastChecker/linglong.yaml
- io.github.ContrastChecker/patches/fix_cc.patch
> build: add app ContrastChecker

- io.github.pokemon-qt/linglong.yaml
- io.github.pokemon-qt/patches/0001-install.patch
Creating a Pokémon 2D game in C++ with Qt library.
Logs: add app name--pokemon-qt
> build: add app pokemon-qt

- io.github.Qt-Mi-Paint/linglong.yaml
- io.github.Qt-Mi-Paint/patches/0001-fix-install.patch
Aplicación para graficar con el mouse.
log: add software--Qt-Mi-Paint
> build: add Qt-Mi-Paint

- io.github.cutenp/linglong.yaml
一个可爱的记事本。基于QML。
Log: finish app cutenp.
> build: add app cutenp

- io.github.cyber-calculator/linglong.yaml
- io.github.cyber-calculator/patches/fix-001.patch
一个计算器小工具，界面更加美观。
Log: finish app cyber-calculator.
> build: add app cyber-calculator

- io.github.BlueMoon/linglong.yaml
- io.github.BlueMoon/patches/fix-001.patch
专为桌面环境设计的蓝牙管理器。
Log: finish app BlueMoon.
> build: add app BlueMoon

- io.github.QtMineSweep/linglong.yaml
- io.github.QtMineSweep/patches/fix-001.patch
一款扫雷小游戏.
Log: finish app QtMineSweep.
> build: add app QtMineSweep

- io.github.phototonic/linglong.yaml
- io.github.phototonic/patches/fix-001.patch
Phototonic 是一个使用 Qt 和 Exiv2 构建的图像查看器和组织器，根据 GNU 通用公共许可证 v3 发布。
Log: finish app phototonic.
> build: add app phototonic

- io.github.15-puzzleQt/linglong.yaml
- io.github.15-puzzleQt/patches/0001-install.patch
15-puzzleQt game.
Logs: add app name--15-puzzleQt
> build: add app 15-puzzleQt

- io.github.Qt-text-editor/linglong.yaml
- io.github.Qt-text-editor/patches/fix_qte.patch
> build: add app Qt-text-editor

- io.github.widgetci/linglong.yaml
- io.github.widgetci/patches/fix_widgetci.patch
> build: add app widgetci.

- io.github.qt_pong_game/linglong.yaml
- io.github.qt_pong_game/patches/0001-install.patch
pong game.
Logs: add app name--qt_pong_game
> build: add app qt_pong_game

- io.github.youtubedl/linglong.yaml
- io.github.youtubedl/patches/fix_ytdl.patch
> build: add app youtubedl

- io.github.Qt-Flappy-Bird/linglong.yaml
- io.github.Qt-Flappy-Bird/patches/0001-install.patch
Using C++&Qt, a visual programming widget. Ideas from the famous game "Flappy Bird". 
Logs: add app name--Qt-Flappy-Bird
> add app Qt-Flappy-Bird

- io.github.rgbtest/linglong.yaml
- io.github.rgbtest/patches/0001-install.patch
rgbtest - LCD Monitor Dead Pixel Test
Log: add software name--rgbtest
> build: add rgbtest

- io.github.codequery/linglong.yaml
- io.github.codequery/patches/add-desktop-file-patch.patch
- io.github.codequery/patches/install-desktop-file-patch.patch
Finish build codequery for ll-build
Log: 完成codequery的编译
> build: add codequery

- io.github.Euclase/linglong.yaml
- io.github.Euclase/patches/0001-install.patch
A painter’s palette for the users.
Log: add software name--Euclase
> build: add Euclase

- io.github.bezitopo/linglong.yaml
- io.github.bezitopo/patches/add-desktop-file-patch.patch
- io.github.bezitopo/patches/install-desktop-file-patch.patch
Finish build bezitopo for ll-build
Log: 完成bezitopo的编译
> build: add bezitopo

- io.github.pineapple-music/linglong.yaml
一款自制音乐播放器。
Log: finish app pineapple-music.
> build: add pineapple-music

- io.github.QtMemoryGame/linglong.yaml
- io.github.QtMemoryGame/patches/0001-install.patch
also called pairs.
Logs: add app name--QtMemoryGame
> build: add app QtMemoryGame

- io.github.SArtificialNeuralWeb/linglong.yaml
- io.github.SArtificialNeuralWeb/patches/0001-install.patch
Teaching product system
Log: add software name--SArtificialNeuralWeb
> build: add SArtificialNeuralWeb

- io.github.f-crm/linglong.yaml
- io.github.f-crm/patches/0001-install.patch
Customer Relations Management for Freelancers and Individual Contractors.
Log: add software name--f-crm
> build: add f-crm

- io.github.torrent-file-editor/linglong.yaml
Qt based GUI tool designed to create and edit .torrent files. This shows full content of .torrent file and allow to change any fields.
log: add app--torrent-file-editor
> build: add torrent-file-editor

- rtmidi/linglong.yaml
一些应用程序所需要的依赖包,路径已检查是正常的。
Log: finish lib rtmidi.
> build: add lib rtmidi

- io.github.qmqtt-plot/linglong.yaml
- io.github.qmqtt-plot/patches/0001-fix-install.patch
A Qt5 app that plots timestamped MQTT data.
log: add software-- qmqtt-plot
> build: add qmqtt-plot

- io.github.pawxel/linglong.yaml
- io.github.pawxel/patches/0001-install.patch
add the patch for pawxel.
Log: update software name--pawxel
> build: update pawxel

- io.github.mpz/linglong.yaml
- io.github.mpz/patches/0001-install.patch
add the patche for mpz.
Log: update software name--mpz
> build: update mpz

- io.github.Qt-weiqi/linglong.yaml
- io.github.Qt-weiqi/patches/0001-install.patch
Finish build Qt-weiqi for ll-build
Log: 完成App:Qt-weiqi的编译
> build: add Qt-weiqi

- io.github.HTYClock/linglong.yaml
- io.github.HTYClock/patches/0001-install.patch
Finish build HTYClock for ll-build
Log: 完成App:HTYClock的编译
> build: add HTYClock

- io.github.UEFITool/linglong.yaml
- io.github.UEFITool/patches/fix-desktop.patch
一款图像查看器和编辑器。
Log: finish UEFITool.
> build: add UEFITool

- io.github.HTYAudioRecorder/linglong.yaml
- io.github.HTYAudioRecorder/patches/0001-install.patch
Finish build HTYAudioRecorder for ll-build
Log: 完成App: HTYAudioRecorder 的编译
> build: add HTYAudioRecorder

- setuptools/linglong.yaml
finish build setuotools lib of python for ll-builder.
log: 完成setuotools的编译。
> build: add setuotools

- io.github.PremiereSubtitle/linglong.yaml
- io.github.PremiereSubtitle/patches/0001-fix-install.patch
字幕导出小工具.
log: add software --PremimreSubtitle
> build: add PremiereSubtitle

- extra-cmake-modules/linglong.yaml
Extra CMake Modules , or ECM.
Logs: update lib name--extra-cmake-modules
> build: update lib extra-cmake-modules

- io.github.TTKLinksGame/linglong.yaml
- io.github.TTKLinksGame/patches/0001-install.patch
Finish build TTKLinksGame for ll-build
Log: 完成App:TTKLinksGame的编译
> build: add TTKLinksGame

- poppler-data/linglong.yaml
Log: place poppler-data.pc to correct location
> fix: poppler-data pkgconfig

- io.github.Frog-Archiver/linglong.yaml
- io.github.Frog-Archiver/patches/fix_install.patch
Frog Archiver is compression tools for any files you have.
Logs: add app name--Frog-Archiver
> build: add app Frog-Archiver

- pcl/linglong.yaml
Finish build pcl  for ll-build
Log: 完成lib:pcl 的编译
> build: add pcl

- io.github.QtTableEditor/linglong.yaml
- io.github.QtTableEditor/patches/0001-fix-install.patch
Desktop application for creating and editing spreadsheets based on C++ Qt Toolkit.
log: add software--QtTableEditor
> build: add QtTableEditor

- io.github.openChecksum/linglong.yaml
- io.github.openChecksum/patches/install.patch
> build: add openChecksum

- io.github.ImageToAscii/linglong.yaml
- io.github.ImageToAscii/patches/add-desktop-file-patch.patch
- io.github.ImageToAscii/patches/install-desktop-file-patch.patch
> build: add ImageToAscii

- io.github.ImageQt/linglong.yaml
- io.github.ImageQt/patches/0001-fix-install.patch
Image viewer powered by Qt 5.8.0
log: upload software--ImageQt
> build: add ImageQt

- io.github.gcalc/linglong.yaml
- io.github.gcalc/patches/install.patch
Log: 完成App：gcalc的编译
说明：无可用Icon文件
> build: add gcalc

- io.github.TulpaDiary/linglong.yaml
- io.github.TulpaDiary/patches/add-desktop.patch
Log: 完成App： TulpaDiary的编译
说明：无可用Icon
> build: add TulpaDiary

- io.github.Inventory-Management/linglong.yaml
- io.github.Inventory-Management/patches/0001-fix-install.patch
Inventory-Management库存管理.
log: add software--Inventory-Management
> build: add Inventory-Management

- io.github.orion/linglong.yaml
- io.github.orion/patches/install.patch
Log: 完成App：orion的编译
说明：无可用Icon
> build: add orion

- io.github.RoboSim/linglong.yaml
- io.github.RoboSim/patches/0001-install.patch
Robotic Arm 3D move simulator.
Logs: add app name--RoboSim
> build: add app RoboSim

- io.github.mixcalc/linglong.yaml
- io.github.mixcalc/patches/add-desktop-file-patch.patch
- io.github.mixcalc/patches/install-desktop-file-patch.patch
> build: add mixcalc

- io.github.ElementaryCellularAutomaton/linglong.yaml
- io.github.ElementaryCellularAutomaton/patches/add-desktop-file-patch.patch
- io.github.ElementaryCellularAutomaton/patches/install-desktop-file-patch.patch
Log: 完成app：ElementaryCellularAutomaton的编译
> build: add ElementaryCellularAutomaton

- io.github.tspsg/linglong.yaml
> build: add tspsg

- io.github.PathFinder/linglong.yaml
- io.github.PathFinder/patches/0001-install.patch
> build: add PathFinder

- io.github.fraqtive/linglong.yaml
> build: add fraqtive

- io.github.Note-App/linglong.yaml
- io.github.Note-App/patches/fix_na.patch
> build: add app Note-App

- io.github.speedtest/linglong.yaml
- io.github.speedtest/patches/fix-001.patch
一款网络速度检测工具，可以以图形化的曲线形式检测你的网络流量。
Log: finish app speedtest.
> build: add app speedtest

- io.github.dbManagerApp/linglong.yaml
- io.github.dbManagerApp/patches/fix_dma.patch
> build: add app dbManagerApp

- com.gitee.notepad--/linglong.yaml
- com.gitee.notepad--/patches/ab.patch
> build: add NotePad--

- io.github.qml-notepad/linglong.yaml
- io.github.qml-notepad/patches/fix-001.patch
qml记事本。
Log: finish qml-notepad.
> build: add qml-notepad

- io.gitlab.gimp/linglong.yaml
- io.gitlab.gimp/patches/fix_desktop.patch
The GNU Image Manipulation Program.
Logs: add app name--gimp
> build: add app gimp

- io.github.qTorrent/linglong.yaml
- io.github.qTorrent/patches/fix_unixconf.patch
> build: add app qTorrent

- io.github.qt5-file-icon-generator/linglong.yaml
- io.github.qt5-file-icon-generator/patches/0001-fix-install.patch
file-icon-generator.
log: add software--qt5-file-icon-generator
> build: add qt5-file-icon-generator

- io.github.Tankoop/linglong.yaml
- io.github.Tankoop/patches/0001-install.patch
Tankoop is a simple arcade game that is created using the QT Application Framework.  
Logs: add app name--Tankoop
> add app Tankoop

- io.github.HiDPI-Fixer/linglong.yaml
- io.github.HiDPI-Fixer/patches/0001-install.patch
Qt app that automates fractional scaling configuration on X11 desktops
Log: add software name--HiDPI-Fixer
> build: add HiDPI-Fixer

- io.github.birdtray/linglong.yaml
Finish build birdtray for ll-build
Log: 完成App：birdtray的编译
> build: add birdtray

- io.github.WordFun/linglong.yaml
- io.github.WordFun/patches/0001-install.patch
QT based C++ simple word search game.
Logs: add app name--WordFun
> build: add app WordFun

- io.github.Minefield/linglong.yaml
- io.github.Minefield/patches/install.patch
> build: add Minefield

- io.github.meow-sql/linglong.yaml
- io.github.meow-sql/patches/0001-install.patch
Finish build meow-sql for ll-build
缺官方依赖
Log: 完成App:meow-sql的编译
> build: add meow-sql

- io.github.Snake/linglong.yaml
- io.github.Snake/patches/fix_Snake.patch
> build: add app Snake

- io.github.Bomboman/linglong.yaml
- io.github.Bomboman/patches/0001-install.patch
Bomboman.
Logs: add app name--Bomboman
> build: add app Bomboman

- io.github.luckybackup/linglong.yaml
- io.github.luckybackup/patches/add-desktop.patch
- io.github.luckybackup/patches/install-desktop.patch
> build: add luckybackup

- io.github.A-Photo-Tool-Libre/linglong.yaml
- io.github.A-Photo-Tool-Libre/patches/0001-install.patch
fix patch.
Logs: update app name--io.github.A-Photo-Tool-Libre
> build: update app io.github.A-Photo-Tool-Libre

- io.github.simsu/linglong.yaml
一款数独小游戏。
Log: finish app simsu.
> build: add app simsu

- io.github.Suqoku/linglong.yaml
- io.github.Suqoku/patches/install.patch
Finish build Suqoku for ll-build
Log: 完成App：Suqoku的编译
> build: add Suqoku

- io.github.notepad/linglong.yaml
- io.github.notepad/patches/fix_np.patch
> build: add app notepad

- OpenColorIO/linglong.yaml
> build: add lib OCIO

- pybind11/linglong.yaml
> build: add lib pybind11

- swig/linglong.yaml
SWIG (Simplified Wrapper and Interface Generator)
log: add lib
> build: add lib swig

- unzip/linglong.yaml
unzipper for pkzip-compressed files.
Logs: add lib unzip
> build: add lib unzip

- minizip-ng/linglong.yaml
- minizip-ng/patches/0001-install.patch
> build: add lib minizip-ng

- vtk/linglong.yaml
- vtk/patches/0001-fix-include.patch
VTK is an open-source software system for image processing, 3D graphics, volume rendering and visualization.
log: add lib
> build: add lib vtk

- exiv2-0.22/linglong.yaml
> build: add lib exiv2-0.22

- io.github.GPXSee/linglong.yaml
> build: add GPXSee

- io.github.qCheckGMail/linglong.yaml
> build: add app qCheckGMail

- Imath/linglong.yaml
> build: add lib Imath

- pystring/linglong.yaml
- pystring/patches/0001-install.patch
> build: add pystring

- io.github.linlogbook/linglong.yaml
- io.github.linlogbook/patches/fix-desktop.patch
> build: add linlogbook

- libsass/linglong.yaml
A libsass command line driver.
Logs: add lib libsass
> build: add lib libsass

- SDL/linglong.yaml
Finish build SDL for ll-build
Log: 完成lib:SDL的编译
> build: add SDL

- io.github.XML-Editor/linglong.yaml
- io.github.XML-Editor/patches/install.patch
XML Editor software written in c++ using QT widget toolkit.
log: add app--XML-Editor
> build: add XML-Editor

- io.github.agm/linglong.yaml
- io.github.agm/patches/add-desktop-file-patch.patch
- io.github.agm/patches/install-desktop-file-patch.patch
Finish build agm for ll-build
Log: 完成agm的编译
> build: add agm

- io.github.fsearch/linglong.yaml
FSearch 是一款快速文件搜索实用程序，其灵感来自 Everything Search Engine。它是用 C 语言编写的，基于 GTK3。
Log: finish fsearch.
> build: add fsearch

- io.github.QT_yanglegeyang_game/linglong.yaml
- io.github.QT_yanglegeyang_game/patches/0001-install.patch
Finish build QT_yanglegeyang_game for ll-build
Log: 完成App: QT_yanglegeyang_game的编译
> build: add QT_yanglegeyang_game

- io.github.MinesweeperFloating/linglong.yaml
- io.github.MinesweeperFloating/patches/0001-install.patch
Finish build MinesweeperFloating for ll-build
Log: 完成App:MinesweeperFloating的编译
> build: add MinesweeperFloating

- io.github.color_picker/linglong.yaml
- io.github.color_picker/patches/0001-install.patch
基于Qt实现的强大取色器
Log: add software name--color_picker
> build: add color_picker

- io.github.fahrplan/linglong.yaml
- io.github.fahrplan/patches/add-desktop.patch
> build: add fahrplan

- io.github.cupcalculator/linglong.yaml
- io.github.cupcalculator/patches/add-desktop.patch
> build: add cupcalculator

- gnuradio/linglong.yaml
Finish build gnuradio for ll-build
Log: 完成App:gnuradio的编译
> build: add gnuradio

- io.github.IanniX/linglong.yaml
- io.github.IanniX/patches/0001-install.patch
> Build：update io.github.IanniX

- io.github.CAN-Bus-GUI-Application/linglong.yaml
- io.github.CAN-Bus-GUI-Application/patches/fix_cb.patch
> build: add app CAN-Bus-GUI-Application

- io.github.DarhonFinance/linglong.yaml
- io.github.DarhonFinance/patches/fix-001.patch
Darhon Finance 是一款功能强大、用户友好的个人理财程序，其中包括允许您管理财务、跟踪信用卡、银行账户、投资和计划支出的功能。 它是一款非常全面的面向台式电脑的软件，并且易于使用。
Log: finish app DarhonFinance.
> build: add DarhonFinance

- io.github.UEFITool/linglong.yaml
- io.github.UEFITool/patches/fix-desktop.patch
> build: modify UEFITool

- io.github.JMSK/linglong.yaml
- io.github.JMSK/patches/fix_JMSK.patch
> build: add app JMSK

- io.github.MarioQT/linglong.yaml
- io.github.MarioQT/patches/0001-install.patch
Finish build MarioQT for ll-build
Log: 完成App: MarioQT的编译
> build: add MarioQT

- io.github.HTYFloatBall/linglong.yaml
- io.github.HTYFloatBall/patches/0001-install.patch
Finish build HTYFloatBall for ll-build
Log: 完成App: HTYFloatBall的编译
> build: add HTYFloatBall

- io.github.tetzle/linglong.yaml
拼图益智游戏，导入自己的图像，完整自己图像的拼图游戏。
Log: finish app tetzle.
> build: add app tetzle

- io.github.sheep_sweeper/linglong.yaml
- io.github.sheep_sweeper/patches/fix-001.patch
Sheepweeper游戏由C ++/QT4实施。这是对著名的扫雷游戏的修改.
Log: finish app sheep_sweeper.
> build: add app sheep_sweeper

- io.github.sudoku-qt5/linglong.yaml
- io.github.sudoku-qt5/patches/fix-001.patch
一款数独游戏。
Log: finish app sudoku-qt5.
> build: add app sudoku-qt5

- io.github.blue-glow/linglong.yaml
- io.github.blue-glow/patches/fix_bg.patch
> build: add app blue-glow

- io.github.HTYEdit/linglong.yaml
- io.github.HTYEdit/patches/0001-install.patch
Finish build HTYEdit for ll-build
Log: 完成App: HTYEdit的编译
> build: add HTYEdit

- io.github.HTYFTP/linglong.yaml
- io.github.HTYFTP/patches/0001-install.patch
Finish build HTYFTP for ll-build
Log: 完成App:HTYFTP的编译
> build: add HTYFTP

- io.github.Snakes/linglong.yaml
- io.github.Snakes/patches/fix-001.patch
- io.github.Snakes/patches/fix-002.patch
贪吃蛇小游戏。
Log: finish app Snake.
> build: add app Snakes

- io.github.TwiniGolf_Qt_Cpp/linglong.yaml
- io.github.TwiniGolf_Qt_Cpp/patches/0001-install.patch
Finish build TwiniGolf_Qt_Cpp for ll-build
Log: 完成App: TwiniGolf_Qt_Cpp的编译
> build: add TwiniGolf_Qt_Cpp

- io.github.HTYGIFPlayer/linglong.yaml
- io.github.HTYGIFPlayer/patches/0001-install.patch
Finish build HTYGIFPlayer for ll-build
Log: 完成App:HTYGIFPlayer的编译
> build: add HTYGIFPlayer

- io.github.HTYVideoSpliter/linglong.yaml
- io.github.HTYVideoSpliter/patches/0001-install.patch
Finish build HTYVideoSpliter for ll-build
Log: 完成App: HTYVideoSpliter的编译
> build: add HTYVideoSpliter

- io.github.HTYBoard/linglong.yaml
- io.github.HTYBoard/patches/0001-install.patch
Finish build HTYBoard for ll-build
Log: 完成App:HTYBoard的编译
> build: add HTYBoard

- io.github.Chess/linglong.yaml
- io.github.Chess/patches/0001-install.patch
Finish build Chess for ll-build
Log: 完成App:Chess的编译
> build: add Chess

- io.github.Tanks/linglong.yaml
- io.github.Tanks/patches/0001-install.patch
Finish build Tanks for ll-build
Log: 完成App: Tanks的编译
> build: add Tanks

- io.github.HTYColorPicker/linglong.yaml
- io.github.HTYColorPicker/patches/0001-install.patch
Finish build HTYColorPicker for ll-build
Log: 完成App: HTYColorPicker的编译
> build: add HTYColorPicker

- io.github.LandlordCardGame/linglong.yaml
- io.github.LandlordCardGame/patches/0001-fix-install.patch
使用Qt 5.2.1实现的单机斗地主游戏，带有简单的人工智能。
log: add software--LandlordCardGame
> build: add LandlordCardGame

- io.github.HTYDeskPet/linglong.yaml
- io.github.HTYDeskPet/patches/0001-install.patch
Finish build HTYDeskPet for ll-build
Log: 完成App: HTYDeskPet的编译
> build: add HTYDeskPet

- io.github.TTKCalendar/linglong.yaml
- io.github.TTKCalendar/patches/0001-install.patch
Finish build TTKCalendar for ll-build 
Log: 完成App:TTKCalendar的编译
> build: add TTKCalendar

- io.github.fifteen-game/linglong.yaml
- io.github.fifteen-game/patches/0001-install.patch
Finish build fifteen-game for ll-build
Log: 完成App: fifteen-game的编译
> build: add fifteen-game

- io.github.TTKSnakeGame/linglong.yaml
- io.github.TTKSnakeGame/patches/0001-install.patch
Finish build TTKSnakeGame for ll-build
Log: 完成App: TTKSnakeGame的编译
> build: add TTKSnakeGame

- io.github.FFBChecker/linglong.yaml
- io.github.FFBChecker/patches/0001-install.patch
Finish build FFBChecker for ll-build
Log: 完成App: FFBChecker的编译
> build: add FFBChecker

- io.github.TTKSudokuGame/linglong.yaml
- io.github.TTKSudokuGame/patches/0001-install.patch
Finish build TTKSudokuGame for ll-build
Log: 完成App:TTKSudokuGame的编译
> build: add TTKSudokuGame

- io.github.Qt-PlantsVsZombies/linglong.yaml
- io.github.Qt-PlantsVsZombies/patches/0001-install.patch
It's a project for my Qt Summer Semester. The goal of the project is to implement a plants vs zombies using Qt.
Logs: add app name--Qt-PlantsVsZombies
> build: add app Qt-PlantsVsZombies

- io.github.Qt-calculator/linglong.yaml
- io.github.Qt-calculator/patches/fix-001.patch
- io.github.Qt-calculator/patches/fix-002.patch
- io.github.Qt-calculator/patches/fix-003.patch
- io.github.Qt-calculator/patches/fix-004.patch
一款计算器小工具。
Log: finish app Qt-calculator.
> build: add app Qt-calculator

- io.github.weatherTray/linglong.yaml
- io.github.weatherTray/patches/0001-install.patch
Finish build weatherTray for ll-build
Log: 完成App: weatherTray的编译
> build: add weatherTray

- net.opencode.Notebook/linglong.yaml
- net.opencode.Notebook/patches/0001-install.patch
Simple software for notes creation and managment.
Logs:add app name--Notebook
> build: add app Notebook

- io.github.HTYHex/linglong.yaml
- io.github.HTYHex/patches/0001-install.patch
Finish build HTYHex for ll-build
Log: 完成App: HTYHex的编译
> build: add HTYHex

- io.github.Geist/linglong.yaml
- io.github.Geist/patches/fix_geist.patch
> build: add app Geist

- io.github.kale/linglong.yaml
- io.github.kale/patches/0001-install.patch
Finish build kale  for ll-build
Log: 完成App:kale的编译
> build: add kale

- fishui/linglong.yaml
一个lib依赖库，上层应用依赖此开发。
Log: finish lib fishui.
> build: add lib fishui

- io.github.klotski/linglong.yaml
- io.github.klotski/patches/0001-install.patch
klotski is a puzzle game.
Logs: add app name--klotski
> build: add app klotski

- io.github.Converter/linglong.yaml
Simple, fast, and powerful: convert your strings with SConverter.
Logs: add app name--Converter
> build: add app Converter

- io.github.U1Files/linglong.yaml
- io.github.U1Files/patches/fix_uqf.patch
> build: add app U1Files

- io.github.Paintpp/linglong.yaml
- io.github.Paintpp/patches/0001-install.patch
A simple bitmap painting program built with Qt.
Logs: add app name--Paintpp
> build: add app Paintpp

- io.github.HashApp/linglong.yaml
- io.github.HashApp/patches/install.patch
finish build HashApp for ll-build
Log: 完成HashApp的编译
> build: add HashApp

- io.github.qtchan/linglong.yaml
- io.github.qtchan/patches/install-desktop.patch
finish build qtchan for ll-build
Log: 完成qtchan的编译
> build: add qtchan

- vncclient/linglong.yaml
> build: add lib vncclient

- io.github.keepassx/linglong.yaml
> build: add app keepassx

- io.github.freedom/linglong.yaml
- io.github.freedom/patches/0001-install.patch
Freedom is the game developed in C++ with the help of Qt framework. The main goal of the project is to master skills of teamwork, project development and programming in C++/Qt.
Logs: QtMusic app name--freedom
> build: add app freedom

- io.github.tinyserial/linglong.yaml
- io.github.tinyserial/patches/0001-install.patch
Finish build tinyserial for ll-build
缺库
Log: 完成App:tinyserial的编译
> build: add tinyserial

- io.github.kalendar/linglong.yaml
- io.github.kalendar/patches/install-desktop.patch
> build: add kalendar

- io.github.Binaly/linglong.yaml
- io.github.Binaly/patches/add-desktop.patch
> build: add Binaly

- io.github.QHeatMap/linglong.yaml
- io.github.QHeatMap/patches/add-desktop-file-patch.patch
- io.github.QHeatMap/patches/install-desktop-file-patch.patch
> build: add QHeatMap

- io.github.QtScrcpy/linglong.yaml
- io.github.QtScrcpy/patches/add-desktop-file-patch.patch
- io.github.QtScrcpy/patches/install-desktop-file-patch.patch
> build: add QtScrcpy

- io.github.sailcut/linglong.yaml
- io.github.sailcut/patches/fix_src.patch
> build: add app sailcut

- io.github.FleetingPasswordManager/linglong.yaml
- io.github.FleetingPasswordManager/patches/fix_fpm.patch
> build: add app FleetingPasswordManager

- io.github.PokerTH-Tracker/linglong.yaml
- io.github.PokerTH-Tracker/patches/add-desktop.patch
> build: add PokerTH-Tracker

- io.github.qtAproximator/linglong.yaml
- io.github.qtAproximator/patches/install-desktop.patch
finish build qtAproximator for ll-build
Log: 完成qtAproximator的编译
> build: add qtAproximator

- io.github.StatisticAnalyzer-CPP-Qt/linglong.yaml
- io.github.StatisticAnalyzer-CPP-Qt/patches/install-desktop.patch
finish build StatisticAnalyzer-CPP-Qt for ll-build
Log: 完成StatisticAnalyzer-CPP-Qt的编译
> build: add StatisticAnalyzer-CPP-Qt

- io.github.QtPhilosophers/linglong.yaml
- io.github.QtPhilosophers/patches/add-desktop.patch
finish build QtPhilosophers for ll-build
Log: 完成QtPhilosophers的编译
> build: add QtPhilosophers

- io.github.timekeeper/linglong.yaml
- io.github.timekeeper/patches/install-desktop.patch
> build: add timekeeper

- io.github.kakuro/linglong.yaml
- io.github.kakuro/patches/install-desktop.patch
> build: add kakuro

- io.github.qSdrSwr/linglong.yaml
- io.github.qSdrSwr/patches/0001-install.patch
Qt SWR analyser using an SDR and soapy_power
Log: add software name--qSdrSwr
> build: add qSdrSwr

- mypaint-brushes/linglong.yaml
Brushes used by MyPaint and other software using libmypaint.
Logs: add lib mypaint-brushes
> build: add lib mypaint-brushes

- io.github.checksgui/linglong.yaml
- io.github.checksgui/patches/install-desktop.patch
> build: add checksgui

- io.github.qwood/linglong.yaml
- io.github.qwood/patches/0001-install.patch
Data structure visualization tool based on Qt.
Log: add software name--qwood
> build: add qwood

- io.github.TORQUEView/linglong.yaml
- io.github.TORQUEView/patches/install-desktop.patch
> build: add TORQUEView

- io.github.OmegaRPG/linglong.yaml
- io.github.OmegaRPG/patches/install-desktop.patch
> build: add OmegaRPG

- io.github.APA_QT/linglong.yaml
- io.github.APA_QT/patches/install-desktop.patch
> build: add APA_QT

- io.github.diecat/linglong.yaml
- io.github.diecat/patches/add-desktop.patch
> build: add diecat

- io.github.plumber/linglong.yaml
- io.github.plumber/patches/0001-install.patch
Finish build plumber for ll-build
Log: 完成App:plumber的编译
> build: add plumber

- io.github.r49/linglong.yaml
- io.github.r49/patches/add-desktop.patch
> build: add r49

- io.github.ColorCode/linglong.yaml
- io.github.ColorCode/patches/install.patch
> build: add ColorCode

- io.github.ogappm/linglong.yaml
- io.github.ogappm/patches/install.patch
> build: add ogappm

- io.github.IconThemeBrowser/linglong.yaml
- io.github.IconThemeBrowser/patches/fix_itb.patch
> build: add app IconThemeBrowser

- io.github.glate/linglong.yaml
- io.github.glate/patches/0001-install.patch
Finish build glate for ll-build
Log: 完成App:glate的编译
> build: add glate

- io.github.TextEditor-Qt/linglong.yaml
- io.github.TextEditor-Qt/patches/fix-001.patch
一款使用qt框架编写的记事本软件。
Log: finish TextEditor-Qt.
> build: add TextEditor-Qt

- io.github.yourik/linglong.yaml
- io.github.yourik/patches/0001-fix-install.patch
Yourik The Intergalactic Rabbit is the animal rights-themed arcade game.
log: add game
> build: add yourik

- io.github.xosview/linglong.yaml
> build: add app xosview

- xalan-c/linglong.yaml
XSLT processor for transforming XML into HTML, text, or other XML types.
Logs: add lib xalan-c
> build: add lib xalan-c

- io.github.fractgen/linglong.yaml
> build: add app fractgen

- io.github.Guitar/linglong.yaml
- io.github.Guitar/patches/fix-desktop.patch
> build: add Guitar

- com.debian.opl3bankeditor/linglong.yaml
> build: add app opl3bankeditor

- io.github.showifcfg/linglong.yaml
- io.github.showifcfg/patches/fix-desktop.patch
> build: add showifcfg

- io.github.cutegomoku/linglong.yaml
- io.github.cutegomoku/patches/fix-desktop.patch
> build: add cutegomoku

- io.github.NineChess/linglong.yaml
- io.github.NineChess/patches/0001-1.patch
> build: add NineChess

- io.github.qelectrotech/linglong.yaml
- io.github.qelectrotech/patches/fix_001.patch
> build: add app qelectrotech

- io.github.qwinff/linglong.yaml
- io.github.qwinff/patches/fix_001.patch
> build: add app qwinff

- io.github.qdmr/linglong.yaml
- io.github.qdmr/patches/0001-install.patch
> build: add qdmr

- io.github.Saaghar/linglong.yaml
> build: add Saaghar

- io.github.hoverclock-qt/linglong.yaml
- io.github.hoverclock-qt/patches/0001-1.patch
Finish build hoverclock-qt for ll-build
Log: 完成hoverclock-qt的编译
> build: add hoverclock-qt

- io.github.softfm-gui/linglong.yaml
- io.github.softfm-gui/patches/add-desktop.patch
> build: add softfm-gui

- io.github.mbmp/linglong.yaml
- io.github.mbmp/patches/fix-desktop.patch
> build: add mbmp

- io.github.uKiris/linglong.yaml
- io.github.uKiris/patches/add-desktop.patch
> build: add uKiris

- io.github.AnimationMaker/linglong.yaml
- io.github.AnimationMaker/patches/fix-desktop.patch
> build: add AnimationMaker

- .gitignore
- .reuse/dep5
- org.dde.calendar/linglong.yaml
> build: add org.dde.calendar

- freetype/linglong.yaml
> build: add lib freetype

- Log4Qt/linglong.yaml
> build: add lib Log4Qt

- io.github.afce/linglong.yaml
Finish build afce for ll-build
Log: 完成afce的编译
> build: add afce

- KConfig/linglong.yaml
> build: add lib   KConfig

- kidletime/linglong.yaml
> build: add lib kidletime

- io.github.quteqoin/linglong.yaml
> build: add quteqoin

- io.github.antimicro/linglong.yaml
Finish build antimicro for ll-build
Log: 完成antimicro的编译
> build: add antimicro

- io.github.DiagramTool/linglong.yaml
- io.github.DiagramTool/patches/0001-install.patch
A Software For Draw UML Diagram
Log: add software name--DiagramTool
> build: add DiagramTool

- io.github.NetSpeed/linglong.yaml
- io.github.NetSpeed/patches/0001-fix-install.patch
NetSpeed 是一款轻量的实时网速悬浮窗口（支持任意 Linux 发行版）.
log: add app
> build: add NetSpeed

- kcontacts/linglong.yaml
> build: add lib kcontacts

- io.github.Bonzomatic/linglong.yaml
> build: add Bonzomatic

- io.github.Advanced_Photo/linglong.yaml
- io.github.Advanced_Photo/patches/fix-desktop.patch
> build: add Advanced_Photo

- io.github.BeamerPresenter/linglong.yaml
- io.github.BeamerPresenter/patches/0001-install.patch
Modular multi-screen pdf presentation viewer
Log: add software name--BeamerPresenter
> build: add BeamerPresenter

- io.github.qtmm/linglong.yaml
- io.github.qtmm/patches/add-desktop.patch
> build: add qtmm

- io.github.dust3d/linglong.yaml
- io.github.dust3d/patches/0001-1.patch
Finish build dust3d for ll-build
Log: 完成dust3d的编译
> build: add dust3d

- io.github.gclc/linglong.yaml
- io.github.gclc/patches/0001-install.patch
GCLC is a mathematical software tool for producing high-quality mathematical illustrations
Log: add software name--gclc
> build: add gclc

- knotifications/linglong.yaml
Desktop notifications.
log: add lib
> build: add knotifications

- io.github.ptcollab/linglong.yaml
pxtone collab 基于 pxtone collage，这是由 Cave Story 和 Kero Blaster 的创建者 Pixel 开发的音乐编辑器。
Log: finish app ptcollab.
> build: add app ptcollab

- syntax-highlighting/linglong.yaml
A simple note taking application that automatically saves your work.
log: add lib
> build: add syntax-highlighting

- kio/linglong.yaml
Network transparent access to files and data.
log: add lib
> build: add kio

- solid/linglong.yaml
Desktop hardware abstraction.
log:add lib
> build: add solid

- io.github.dukto/linglong.yaml
- io.github.dukto/patches/0001-install.patch
A simple, fast and multi-platform file transfer tool for LAN users
Log: add software name--dukto
> build: add dukto

- attica/linglong.yaml
> build: add lib attica

- kbookmarks/linglong.yaml
Bookmarks management library.
log: add lib
> build: add kbookmarks

- kxmlgui/linglong.yaml
Framework for managing menu and toolbar actions
log: add lib
> build: add kxmlgui

- sonnet/linglong.yaml
Multi-language spell checker.
log: add lib
> build: add sonnet

- libconfuse/linglong.yaml
Small configuration file parser library for C.
Logs: add lib libconfuse
> build: add lib libconfuse

- ktextwidgets/linglong.yaml
Text editing widgets.
log: add lib
> build: add lib ktextwidgets

- libftdi/linglong.yaml
- libftdi/patches/fix_install.patch
The libFTDI to talk to FTDI chips.
Logs: add lib libftdi
> build: add lib libftdi

- passwordfile/linglong.yaml
C++ library to read/write passwords from/to encrypted files.
Logs: add lib passwordfile
> build: add lib passwordfile

- qtutilities/linglong.yaml
Common Qt related C++ classes and routines used by my applications such as dialogs, widgets and models.
Logs: add lib qtutilities
> build: add lib qtutilities

- kiconthemes/linglong.yaml
Icon GUI utilities.
log: add lib
> build: add lib kiconthemes

- kconfigwidgets/linglong.yaml
Widgets for configuration dialogs.
log: add lib
> build: add lib kconfigwidgets

- OpenSceneGraph/linglong.yaml
Log: add lib name--OpenSceneGraph
> build: add lib OpenSceneGraph

- SFML/linglong.yaml
> build: add lib SFML

- hidapi/linglong.yaml
> build: add lib hidapi

- JUCE/linglong.yaml
> build: add lib JUCE

- protobuf/linglong.yaml
> build: add lib protobuf

- qscintilla/linglong.yaml
> build: add lib qscintilla

- the-libs/linglong.yaml
> build: add the-libs

- gsl/linglong.yaml
> build: add lib gsl

- zstd/linglong.yaml
zstd fast compression library.
Logs: add lib zstd
> build: add lib zstd

- OCCT/linglong.yaml
- OCCT/patches/0001-fix-include.patch
This directory contains sources of Open CASCADE Technology (OCCT).
log: add lib
> build: add lib OCCT

- pango/linglong.yaml
A library for layout and rendering of text.
Logs: add lib pango
> build: add lib pango

- libmypaint/linglong.yaml
Library for making brushstrokes which is used by MyPaint and other projects.
Logs: add lib libmypaint
> build: add lib libmypaint

- gexiv2/linglong.yaml
- gexiv2/patches/fix_install.patch
GObject-based wrapper around the Exiv2 library.
Logs: add lib gexiv2
> build: add lib gexiv2

- gegl/linglong.yaml
Graph based image processing framework.
Logs: add lib gegl
> build: add lib gegl

- babl/linglong.yaml
Dynamic, any to any, pixel format conversion library.
Logs: add lib babl
> build: add lib babl

- python/linglong.yaml
The Python programming language.
Logs: add lib python
> build: add lib python

- cpp-utilities/linglong.yaml
Common C++ classes and routines used by my applications such as argument parser, IO and conversion utilities.
Logs: add lib cpp-utilities
> build: add lib cpp-utilities

- json-glib/linglong.yaml
Library providing GLib serialization and deserialization for the JSON format.
Logs: add lib json-glib
> build: add lib json-glib

- gobject-introspection/linglong.yaml
Introspection system for GObject-based libraries.
Logs: add lib gobject-introspection
> build: add lib gobject-introspection

- kjobwidgets/linglong.yaml
Widgets for showing progress of asynchronous jobs.
log: add lib
> build: add kjobwidgets

- SDL_mixer/linglong.yaml
> build: add SDL_mixer

- flex/linglong.yaml
flex is a tool for generating scanners: programs which recognize lexical patterns in text.
log: add lib
> build: add flex

- libglu/linglong.yaml
> build: add libglu

- libqtxdg/linglong.yaml
Finish build libqtxdg for ll-build
Log: 完成Lib:libqtxdg的编译
> build: add libqtxdg

- automake1.15.0/linglong.yaml
This is Automake, a Makefile generator.
log: add a lib
> build: add automake1.15.0

- io.github.peg-e/linglong.yaml
Peg-E 是一款棋子接龙游戏，您可以跳过棋子来将他们从中删除，最终试图消除除一个之外的所有成员。这棋盘是随机生成的，有 100 个难度级别。游戏 自动保存，并具有撤消重做功能。棋子可以水平移动，垂直和对角线。
Log: finish app peg-e.
> build: add app peg-e

- io.github.cuterest/linglong.yaml
- io.github.cuterest/patches/fix-001.patch
CuteRest 是专用于 JSON...以及 XML 的 REST 客户端工具。
Log: finish app cuterest.
> build: add app cuterest

- io.github.cutemaze/linglong.yaml
CuteMaze 是一款简单的自上而下游戏，其中迷宫是随机生成的,使用几种不同算法中的一种。你移动角色穿过迷宫，同时寻找目标（默认情况下是奶酪）——游戏是 一旦所有这些目标都实现了，我们就获胜了。
Log: finsih app cutemaze.
> build: add app cutemaze

- io.github.HotShots/linglong.yaml
- io.github.HotShots/patches/fix-desktop.patch
> build: add HotShots

- io.github.QtTimeTimer/linglong.yaml
- io.github.QtTimeTimer/patches/0001-1.patch
finish build QtTimeTimer for ll-build
Log: 完成QtTimeTimer的编译
> build: add QtTimeTimer

- io.github.mathmod/linglong.yaml
- io.github.mathmod/patches/0001-install.patch
Mathematical modelling software
Log: add software name--mathmod
> build: add mathmod

- io.github.qisoburn/linglong.yaml
- io.github.qisoburn/patches/fix-desktop.patch
> build: add qisoburn

- io.github.QMednafen/linglong.yaml
- io.github.QMednafen/patches/add-desktop.patch
> build: add QMednafen

- io.github.OPN2BankEditor/linglong.yaml
- io.github.OPN2BankEditor/patches/add-desktop.patch
> build: add OPN2BankEditor

- io.github.Qt-SESAM/linglong.yaml
- io.github.Qt-SESAM/patches/0001-install.patch
c't SESAM Password Manager (Qt version)
Log: add software name--Qt-SESAM
> build: add Qt-SESAM

- io.github.videodownloader/linglong.yaml
A video downloader with Qt GUI.
Logs: add app name--videodownloader
> build: add app videodownloader

- capstone/linglong.yaml
> fix: capstone -fPIC

- io.github.apk-icon-editor/linglong.yaml
- io.github.apk-icon-editor/patches/0001-install.patch
Finish build apk-icon-editor for ll-build
Log: 完成App:apk-icon-editor的编译
> build: add apk-icon-editor

- io.github.labelbuddy/linglong.yaml
- io.github.labelbuddy/patches/0001-1.patch
Finish build labelbuddy for ll-build
Log: 完成labelbuddy的编译
> build: add labelbuddy

- io.github.5Com/linglong.yaml
- io.github.5Com/patches/0001-install.patch
Serial port access application
Log: add software name--5Com
> build: add 5Com

- io.github.theGrades/linglong.yaml
- io.github.theGrades/patches/0001-install.patch
3rd party theSuite app for grade logging and GPA calculation
Log: add software name--theGrades
> build: add theGrades

- io.github.thePixel/linglong.yaml
- io.github.thePixel/patches/0001-install.patch
Screen Capture Tool
Log: add software name--thePixel
> build: add thePixel

- io.github.PlotJuggler/linglong.yaml
- io.github.PlotJuggler/patches/0001-install.patch
The Time Series Visualization Tool that you deserve.
Log: add software name--PlotJuggler
> build: add PlotJuggler

- io.github.gapQBE/linglong.yaml
- io.github.gapQBE/patches/0001-install.patch
a multi platform and multi sql engines QBE
Log: add software name--gapQBE
> build: add gapQBE

- io.github.doublecontact/linglong.yaml
- io.github.doublecontact/patches/fix_install.patch
> build: add doublecontact

- io.github.traceshark/linglong.yaml
- io.github.traceshark/patches/0001-install.patch
Finish build traceshark for ll-build
Log: 完成App:traceshark 的编译
> build: add traceshark

- io.github.symqhytum/linglong.yaml
- io.github.symqhytum/patches/0001-install.patch
Symphytum Personal Database Software
Log: add software name--symqhytum
> build: add symqhytum

- io.github.nobleNote/linglong.yaml
- io.github.nobleNote/patches/ab.patch
> build: add nobleNote

- io.github.DivvyDroid/linglong.yaml
Finish build DivvyDroid for ll-build
Log: 完成DivvyDroid的编译
> build: add DivvyDroid

- io.github.e2designer/linglong.yaml
> build: add app e2designer

- io.github.PixelFx/linglong.yaml
- io.github.PixelFx/patches/0001-install.patch
Finish build PixelFx for ll-build
Log: 完成App:PixelFx的编译
> build: add PixelFx

- io.github.sshproxy/linglong.yaml
- io.github.sshproxy/patches/install.patch
Finish build sshproxy for ll-build
Log: 完成sshproxy的编译
> build: add sshproxy

- io.github.Qrest/linglong.yaml
- io.github.Qrest/patches/add-desktop.patch
> build: add Qrest

- io.github.element-dots/linglong.yaml
- io.github.element-dots/patches/fix-desktop.patch
> build: add element-dots

- io.github.hddtest/linglong.yaml
- io.github.hddtest/patches/add-desktop.patch
> build: add hddtest

- io.github.marksentence/linglong.yaml
- io.github.marksentence/patches/fix-desktop.patch
> build: add marksentence

- io.github.munt/linglong.yaml
- io.github.munt/patches/0001-install.patch
> build: add munt

- io.github.hpsjam/linglong.yaml
- io.github.hpsjam/patches/0001-install.patch
> build: add hpsjam

- jansson/linglong.yaml
- jansson/patches/ab.patch
> build: add lib jansson

- io.github.midiwake/linglong.yaml
> build: add midiwake

- io.github.logotron/linglong.yaml
- io.github.logotron/patches/add-desktop.patch
> build: add logotron

- io.github.aqueduct/linglong.yaml
- io.github.aqueduct/patches/fix_001.patch
> build: add app aqueduct

- io.github.PointsPicker/linglong.yaml
- io.github.PointsPicker/patches/fix_001.patch
> build: add app PointsPicker

- intltool/linglong.yaml
Log: add dependence name--intltool
> build: add dependence intltool

- io.github.tableau-log-viewer/linglong.yaml
- io.github.tableau-log-viewer/patches/fix_001.patch
- io.github.tableau-log-viewer/patches/fix_002.patch
- io.github.tableau-log-viewer/patches/fix_003.patch
> build: add app tableau-log-viewer

- io.github.Sweetfish/linglong.yaml
- io.github.Sweetfish/patches/fix_install.patch
> build: add Sweetfish

- io.github.QPolygonMaker/linglong.yaml
- io.github.QPolygonMaker/patches/0001-1.patch
> build: add QPolygonMaker

- io.github.freeLib/linglong.yaml
> build: add freeLib

- io.github.DSRemote/linglong.yaml
- io.github.DSRemote/patches/fix_desktop.patch
Log: 完成APP：DSRemote的编译。
重新使用自带desktop文件。
版本号已升级。
> build: add DSRemote

- io.github.boxes-server/linglong.yaml
- io.github.boxes-server/patches/fix-desktop.patch
> build: add boxes-server

- io.github.CCR-Plus/linglong.yaml
- io.github.CCR-Plus/patches/fix_desktop.patch
Log: 完成对App：CCR-Plus的编译
修复对icon名字重复率太高的问题
版本号已升级
> build: add CCR-Plus

- pycairo/linglong.yaml
> build: add lib pycairo

- dtkdeclarative/linglong.yaml
update dtkdeclarative.
Log: update dtkdeclarative
> build： update dtkdeclarative to 5.6.22

- io.github.tanglet/linglong.yaml
Single player variant of Boggle.
Log: add software name--tanglet
> build: add tanglet

- io.github.sudoku-solver/linglong.yaml
- io.github.sudoku-solver/patches/0001-install.patch
Sudoku solver
Log: add software name--sudoku-solver
> build: add sudoku-solver

- io.github.qnetstatview/linglong.yaml
- io.github.qnetstatview/patches/0001-install.patch
program that will show you detailed listings of all TCP and UDP endpoints on your system, including the local and remote addresses and state of TCP connections.
Log: add software name--qnetstatview
> build: add qnetstatview

- io.github.evoplex/linglong.yaml
- io.github.evoplex/patches/0001-install.patch
- io.github.evoplex/patches/0002-install.patch
Evoplex is a fast, robust and extensible platform for developing agent-based models and multi-agent systems on networks. It's available for Windows, Linux and macOS.
Log: add software name--evoplex
> build: add evoplex

- io.github.tbe/linglong.yaml
- io.github.tbe/patches/fix_install.patch
The Butterfly Effect, a realistic physics simulation game.
Logs: add app name--tbe
> build: add app tbe

- io.github.fotowall/linglong.yaml
- io.github.fotowall/patches/fix_build.patch
- io.github.fotowall/patches/fix_install.patch
Pictures collage & creativity tool.
Logs: add app name--fotowall
> build: add app fotowall

- io.github.osm/linglong.yaml
- io.github.osm/patches/fix_build.patch
Open sound meter. FFT based application for tuning sound systems.
Logs: add app name--osm
> build: add app osm

- QEverCloud/linglong.yaml
Unofficial Evernote Cloud API for Qt 5.
Log: add lib name--QEverCloud
> build: add lib  QEverCloud

- xdotool/linglong.yaml
fake keyboard/mouse input, window management, and more.
Logs: add lib xdotool
> build: add lib xdotool

- io.github.PacketSender/linglong.yaml
- io.github.PacketSender/patches/0001-install.patch
Network utility for sending / receiving TCP, UDP, SSL, HTTP
Log: add software name--PacketSender
> build: add PacketSender

- io.github.qnapi/linglong.yaml
- io.github.qnapi/patches/0001-install.patch
Qt-based, multi-engine, multi-platform subtitle downloader
Log: add software name--qnapi
> build: add qnapi

- org.deepin.manual/linglong.yaml
- org.deepin.manual/patches/fix-linglong.patch
> feat: add deepin manual

- io.github.writernote-qt/linglong.yaml
- io.github.writernote-qt/patches/0001-install.patch
you can record audio as you write, and listen to it again seeing what you have written for every second of the audio.
Log: add software name--writernote-qt
> build: add writernote-qt

- io.github.mfet/linglong.yaml
- io.github.mfet/patches/0001-install.patch
This program aims to automatically generate the timetable of a school, high-school or university.
Log: add software name--mfet
> build: add mfet

- io.github.seer/linglong.yaml
- io.github.seer/patches/0001-install.patch
Seer - a gui frontend to gdb for Linux
Log: add software name--seer
> build: add seer

- io.github.socnetv/linglong.yaml
- io.github.socnetv/patches/0001-install.patch
Social Network Analysis and Visualization software application.
Log: add software name--socnetv
> build: add socnetv

- io.github.Eqonomize/linglong.yaml
Eqonomize! Personal accounting (cross-platform)
Log: add software name--Eqonomize
> build: add Eqonomize

- io.github.LANDrop/linglong.yaml
Drop any files to any devices on your LAN.
Log: add software name--LANDrop
> build: add LANDrop

- io.github.hydraulics_channel_gvf/linglong.yaml
- io.github.hydraulics_channel_gvf/patches/0001-install.patch
Application that calculate water-surface elevation in prismatic channel with gradually varied flow.
Log: add software name--hydraulics_channel_gvf
> build: add hydraulics_channel_gvf

- io.github.sfbrename/linglong.yaml
- io.github.sfbrename/patches/0001-install.patch
Bulk file renamer
Log: add software name--sfbrename
> build: add sfbrename

- io.github.Open-Typer/linglong.yaml
- io.github.Open-Typer/patches/0001-install.patch
- io.github.Open-Typer/patches/0002-install.patch
A free and open source typing tutor program
Log: add software name--Open-Typer
> build: add Open-Typer

- io.github.MiniZincIDE/linglong.yaml
- io.github.MiniZincIDE/patches/0001-install.patch
The MiniZinc IDE
Log: add software name--MiniZincIDE
> build: add MiniZincIDE

- io.github.ZeGrapher/linglong.yaml
2D Math and Data plotter.
Log: add software name--ZeGrapher
> build: add ZeGrapher

- io.github.easy-slideshow/linglong.yaml
- io.github.easy-slideshow/patches/0001-install.patch
Slideshow that displays the images of multiple folders in a randomized order.
Log: add software name--easy-slideshow
> build: add easy-slideshow

- io.github.lithomaker/patches/0001-install.patch
Log: update icon name--lithomaker
> update: change the icon for lithomaker

- dtkdeclarative/linglong.yaml
> chore: update dtkdeclarative to 5.6.24

- io.github.zNotes/patches/0001-install.patch
Log: update software name--zNotes
> update: change the patch for zNotes

- io.github.marble/linglong.yaml
> build: add marble

- io.github.Molsketch/linglong.yaml
- io.github.Molsketch/patches/0001-install.patch
Molsketch 2D molecular editor
Log: add software name--Molsketch
> build: add Molsketch

- io.github.lyricpad/linglong.yaml
- io.github.lyricpad/patches/0001-install.patch
Qt App Lyrics from web
Log: add software name--lyricpad
> build: add lyricpad

- io.github.netanim/linglong.yaml
- io.github.netanim/patches/0001-install.patch
ns-3 network animator
Log: add software name--netanim
> build: add netanim

- io.github.WiseTagger/linglong.yaml
- io.github.WiseTagger/patches/fix_install.patch
Simple picture tagging tool.
Logs: add app name--WiseTagger
> build: add app WiseTagger

- io.github.DigitalClock4/linglong.yaml
- io.github.DigitalClock4/patches/fix_build.patch
- io.github.DigitalClock4/patches/fix_install.patch
beautiful highly customizable clock with plugins.
应用默认显示一个时钟，设置需要在系统栏的小图标右键。
Logs: add app name--DigitalClock4
> build: add app DigitalClock4

- io.github.deling/linglong.yaml
- io.github.deling/patches/0001-install.patch
Final Fantasy VIII field archive editor
Log: add software name--deling
> build: add deling

- io.github.hyne/linglong.yaml
- io.github.hyne/patches/0001-install.patch
Final Fantasy VIII Save Editor
Log: add software name--hyne
> build: add hyne

- io.github.blackchocobo/linglong.yaml
- io.github.blackchocobo/patches/0001-install.patch
Save Editor For Final Fantasy VII
Log: add software name--blackchocobo
> build: add blackchocobo

- io.github.XaoS/linglong.yaml
- io.github.XaoS/patches/0001-install.patch
Real-time interactive fractal zoomer
Log: add software name--XaoS
> build: add XaoS

- io.github.makoureactor/linglong.yaml
- io.github.makoureactor/patches/0001-install.patch
Final Fantasy VII field archive editor
Log: add software name--makoureactor
> build: add makoureactor

- io.github.texmaker/linglong.yaml
- io.github.texmaker/patches/0001-install.patch
Manual import of Texmaker from released source tarballs downloaded from
Log: add software name--texmaker
> build: add texmaker

- io.github.tea-qt/linglong.yaml
TEA text editor
Log: add software name--tea-qt
> build: add tea-qt

- io.github.EasyPaint/linglong.yaml
- io.github.EasyPaint/patches/0001-install.patch
Yet another painting software
Log: add software name--EasyPaint
> build: add EasyPaint

- io.github.AVIMetaEdit/linglong.yaml
- io.github.AVIMetaEdit/patches/0001-install.patch
AVI metadata editor
Log: add software name--AVIMetaEdit
> build: add AVIMetaEdit

- io.github.MOVMetaEdit/linglong.yaml
- io.github.MOVMetaEdit/patches/0001-install.patch
Basic MOV metadata editor for specific needs
Log: add software name--MOVMetaEdit
> build: add MOVMetaEdit

- io.github.audmes/linglong.yaml
- io.github.audmes/patches/0001-install.patch
Multi-platfrom system for audio measurement through sound card in the PC.
Log: add software name--audmes
> build: add audmes

- io.github.Play-/linglong.yaml
Play! - PlayStation2 Emulator
Log: add software name--Play!
> build: add Play-

- io.github.glaxnimate/linglong.yaml
A simple vector graphics animation program.
Log: add software name--glaxnimate
> build: add glaxnimate

- io.github.skcc/linglong.yaml
Reverse Beacon Network Client
Log: add software name--skcc
> build: add skcc

- io.github.hidracpp/linglong.yaml
- io.github.hidracpp/patches/0001-install.patch
Projeto hidra, versão feita em C++
Log: add software name--hidracpp
> build: add hidracpp

- io.github.Sanmill/linglong.yaml
- io.github.Sanmill/patches/0001-install.patch
Sanmill is an open-source,  program with CUI, Flutter GUI and Qt GUI,sharing and freely distributing the code, tools and data needed to deliver this mill game.
Log: add software name--Sanmill
> build: add Sanmill

- io.github.synthetic-things/linglong.yaml
- io.github.synthetic-things/patches/0001-install.patch
A fantastic factory to make synthetic fruits.
Log: add software name--synthetic-things
> build: add synthetic-things

- io.github.tasveer/linglong.yaml
- io.github.tasveer/patches/fix_install.patch
A simple image browsing and tagging application.
Logs: add app name--tasveer
> build: add app tasveer

- io.github.galaxy-calculator/linglong.yaml
- io.github.galaxy-calculator/patches/fix_install.patch
Galaxy Calculator: Given the size of the Galaxy you can plot the Track the Sun is on and Life might exist.
Logs: add app name--galaxy-calculator
> build: add app galaxy-calculator

- io.github.familiar/linglong.yaml
- io.github.familiar/patches/0001-install.patch
Familiar is a genealogy software
Log: add software name--familiar
> build: add familiar

- io.github.qtResistors/linglong.yaml
- io.github.qtResistors/patches/0001-install.patch
Calculate resistance value and tolerance of resistors
Log: add software name--qtResistors
> build: add qtResistors

- io.github.qvv/linglong.yaml
- io.github.qvv/patches/0001-install.patch
QVV Image Viewer - Qt-based image browser
Log: add software name--qvv
> build: add qvv

- io.github.Stacer/linglong.yaml
- io.github.Stacer/patches/ab.patch
Linux System Optimizer and Monitoring
Log: add software name--stacer
> Build: add app stacer

- qwt/linglong.yaml
add lib qwt
Log: add lib name--qwt
> build: add qwt

- io.github.ukncbtl-qt/linglong.yaml
- io.github.ukncbtl-qt/patches/0001-install.patch
UKNCBTL emulator
Log: add software name--ukncbtl-qt
> build: add ukncbtl-qt

- io.github.evolvotron/linglong.yaml
- io.github.evolvotron/patches/0001-install.patch
Evolvotron is interactive "generative art" software to evolve images/textures/patterns through an iterative process of random mutation and user-selection driven evolution
Log: add software name--evolvotron
> build: add evolvotron

- io.github.vym/linglong.yaml
- io.github.vym/patches/0001-install.patch
View Your Mind
Log: add software name--vym
> build: add vym

- io.github.symphytum/linglong.yaml
- io.github.symphytum/patches/0001-install.patch
Symphytum Personal Database Software
Log: add software name--symphytum
> build: add symphytum

- io.github.giada/linglong.yaml
- io.github.giada/patches/0001-fix.patch
> build: add giada

- io.github.Candle/linglong.yaml
- io.github.Candle/patches/0001-fix-desktop.patch
GRBL controller application with G-Code visualizer written in Qt.
> build: add Candle

- io.github.teeworlds/linglong.yaml
- io.github.teeworlds/patches/0001-fix.patch
A retro multiplayer shooter
log: add game
> build: add teeworlds

- io.github.Clementine/linglong.yaml
Clementine is a modern music player and library organizer for Windows, Linux and macOS.
> build: add Clementine

- io.github.depthmapX/linglong.yaml
- io.github.depthmapX/patches/0001-fix-desktop.patch
multi-platform spatial network analyses software
> build: add depthmapX

- io.github.Heart/linglong.yaml
- io.github.Heart/patches/0001-fix-desktop.patch
> build: add Heart

- io.github.tremotesf2/linglong.yaml
Remote GUI for transmission-daemon
Log: add software name--tremotesf2
> build: add tremotesf2

- io.github.qdraw/linglong.yaml
- io.github.qdraw/patches/0001-install.patch
Qt QGraphicsView drawing
Log: add software name--qdraw
> build: add qdraw

- io.github.QRCodeGenerator/linglong.yaml
> build: add QRCodeGenerator

- io.github.crow-translate/linglong.yaml
Crow Translate is a simple and lightweight translator written in C++ / Qt that allows you to translate and speak text using Google, Yandex, Bing, LibreTranslate and Lingva translate API. You may also be interested in my library QOnlineTranslator used in this project.
> build: add crow-translate

- io.github.M_qml_Bomber/linglong.yaml
- io.github.M_qml_Bomber/patches/0001-fix-desktop.patch
Bomber game written with QML and C++ in Qt Creator Has a settings page, an opportunity to begin a new game etc.
log: add a game
> build: add  M_qml_Bomber

- io.github.M_ImgConvert/linglong.yaml
- io.github.M_ImgConvert/patches/0001-fix-desktop.patch
App for making one image formats from another ones (just for fun) (Qt, C++. Gui)
log: add a sofware
> build: add M_ImgConvert

- io.github.OpenSPH/linglong.yaml
- io.github.OpenSPH/patches/0001-fix-desktop.patch
OpenSPH is a library and a GUI application for hydrodynamic and N-body simulations
> build: add OpenSPH

- io.github.FFQueue/linglong.yaml
- io.github.FFQueue/patches/0001-fix-desktop.patch
> build: add FFQueue

- io.github.EasyBench/linglong.yaml
- io.github.EasyBench/patches/0001-fix-desktop.patch
EasyBench 是一个运行于嵌入式 Linux 平台，集系统监控、设备测试和席位功能配置于一体的软件工具。
> build: add EasyBench

- io.github.porymap/linglong.yaml
- io.github.porymap/patches/0001-fix-desktop.patch
Map editor for pokeemerald, pokefirered, and pokerub
> build: add porymap

- drumstick/linglong.yaml
Drumstick Qt/C++ MIDI libraries.
Logs: add lib drumstick
> build: add lib drumstick

- nlohmann-json3/linglong.yaml
lib nlohmann-json3
log: add lib
> build: lib nlohmann-json3

- io.github.toggldesktop/linglong.yaml
Toggl Desktop app for Windows, Mac and Linux
log: add app
> build: add app toggldesktop

- io.github.AwesomeBump/linglong.yaml
- io.github.AwesomeBump/patches/0001-fix.patch
AwesomeBump is a free program written using Qt library designed to generate normal
log: add app
> build: add app AwesomeBump

- io.github.filmulator-gui/linglong.yaml
- io.github.filmulator-gui/patches/0001-fix.patch
Filmulator --- Simplified raw editing with the power of film.
log: add app
> build: add app filmulator-gui

- io.github.routegen/linglong.yaml
- io.github.routegen/patches/0001-fix-desktop.patch
Route Generator (clone frome SourceForge.net)
log: add app
> build: add app routegen

- io.github.poolviewer/linglong.yaml
- io.github.poolviewer/patches/0001-install.patch
Poolviewer - Opensource Swimovate Poolmate application
Log: add software name--poolviewer
> build: add poolviewer

- io.github.mugi-grep/linglong.yaml
- io.github.mugi-grep/patches/0001-install.patch
Gui grep (and sed) with sessions and history
Log: add software name--mugi-grep
> build: add mugi-grep

- io.github.uConfig/linglong.yaml
- io.github.uConfig/patches/0001-install.patch
Datasheet pinout extractor from PDF and library Stylizer for Kicad.
Log: add software name--uConfig
> build: add uConfig

- io.github.QtBitcoinTrader/linglong.yaml
- io.github.QtBitcoinTrader/patches/0001-install.patch
Secure multi crypto exchange trading client
Log: add software name--QtBitcoinTrader
> build: add QtBitcoinTrader

- io.github.blink/linglong.yaml
- io.github.blink/patches/0001-install.patch
GUI of live indexed grep for source code
Log: add software name--blink
> build: add blink

- io.github.plume-creator/linglong.yaml
- io.github.plume-creator/patches/0001-install.patch
- io.github.plume-creator/patches/0002-install.patch
open-source tool for novelists
Log: add software name--plume-creator
> build: add plume-creator

- io.github.feff/linglong.yaml
- io.github.feff/patches/0001-install.patch
ffmpeg Qt5 GUI
Log: add software name--feff
> build: add feff

- io.github.ardoise/linglong.yaml
- io.github.ardoise/patches/0001-install.patch
- io.github.ardoise/patches/0002-install.patch
The Ardoise is an open source software providing an infinite area to draw small outlines.
Log: add software name--ardoise
> build: add ardoise

- io.github.rdr2view/linglong.yaml
- io.github.rdr2view/patches/0001-install.patch
Open Source Photo and Savegame viewer/editor for RDR 2
Log: add software name--rdr2view
> build: add rdr2view

- io.github.SmillaEnlarger/linglong.yaml
- io.github.SmillaEnlarger/patches/0001-install.patch
you can pick an interesting part of your photo and blow it up to poster size.
Log: add software name--SmillaEnlarger
> build: add SmillaEnlarger

- io.github.hexed/linglong.yaml
- io.github.hexed/patches/0001-install.patch
Binary file hex editor
Log: add software name--hexed
> build: add hexed

- io.github.QText/linglong.yaml
- io.github.QText/patches/0001-fix-desktop.patch
Simple note taking program with multi-folder support and auto-save.
log: add app
> build: add app Qtext

- io.github.Linux-SonivoxEas/linglong.yaml
Sonivox EAS for Linux and Qt
log: add app
> build: add app Linux-SonivoxEas

- io.github.CSV-Analyzer/linglong.yaml
- io.github.CSV-Analyzer/patches/0001-install.patch
It can plot value vs line number/ time value (for only known log formats), and value vs another value scatter graphs.
Log: add software name--CSV-Analyzer
> build: add CSV-Analyzer

- io.github.USG/linglong.yaml
- io.github.USG/patches/0001-fix.patch
USG - free, open source, multi-platform software for evidence ultrasound examinations.
log: add app
> build: add app USG

- io.github.mayo/linglong.yaml
- io.github.mayo/patches/0001-fix-desktop-and-binary-install.patch
3D CAD viewer and converter based on Qt + OpenCascade
log: add app
> build: add app mayo
